HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/CalcByFullDiag.cpp File Reference
CalcByFullDiag.cpp File Reference
#include "CalcByFullDiag.hpp"
#include "input.hpp"
#include "wrapperMPI.hpp"
#include "CalcTime.hpp"
#include "mltplyCommon.hpp"
#include "mltply.hpp"
Functions
int CalcByFullDiag (struct EDMainCalStruct *X)
Parent function for FullDiag mode.
Function Documentation
CalcByFullDiag()
int CalcByFullDiag (struct EDMainCalStruct * X)
Parent function for FullDiag mode.
Parameters
X [in,out] Struct to get information about file header names, dimension of hirbert space, calc type, physical quantities.
Return values
TRUE(=1) normally finished.
FALSE(=0) abnormally finished.
Definition at line 27 of file CalcByFullDiag.cpp.
References EDMainCalStruct::Bind, BindStruct::Check, BindStruct::Def, CheckList::idim_max, DefineList::iInputHam, inputHam(), DefineList::iOutputHam, lapack_diag(), mltply(), output(), outputHam(), phys(), DefineList::St, StartTimer(), stdoutMPI, StopTimer(), v0, v1, and zclear().
Referenced by main().
 {
   int iret=0;
   long int idim;
   fprintf(stdoutMPI, "%s", "######  Start: Setting Hamiltonian.  ######\n\n");
   StartTimer(5100);
   if(X->Bind.Def.iInputHam==FALSE){
     zclear((X->Bind.Check.idim_max + 1)*X->Bind.Check.idim_max, &v0[0][0]);
     zclear((X->Bind.Check.idim_max + 1)*X->Bind.Check.idim_max, &v1[0][0]);
     for (idim = 1; idim <= X->Bind.Check.idim_max; idim++) v1[idim][idim-1] = 1.0;
     mltply(&(X->Bind), X->Bind.Check.idim_max, v0, v1);
   }
   else if(X->Bind.Def.iInputHam==TRUE){
     fprintf(stdoutMPI, "%s", "######  Start: Input Hamiltonian.  ######\n\n");
     inputHam(&(X->Bind));
     fprintf(stdoutMPI, "%s", "######  End  : Input Hamiltonian.  ######\n\n");
   }
   StopTimer(5100);
   fprintf(stdoutMPI, "%s", "######  End  : Setting Hamiltonian.  ######\n\n");
   if(iret != 0) return FALSE;
   if(X->Bind.Def.iOutputHam == TRUE){
     fprintf(stdoutMPI, "%s", "######  Start: Output Hamiltonian.  ######\n\n");
     StartTimer(5500);
     iret=outputHam(&(X->Bind));
     StopTimer(5500);
     fprintf(stdoutMPI, "%s", "######  End  : Output Hamiltonian.  ######\n\n");
     if(iret != 0) return FALSE;
     return TRUE;
   }
   fprintf(stdoutMPI, "%s", "######  Start: Diagonalization.  ######\n\n");
   StartTimer(5200);
   iret=lapack_diag(&(X->Bind));
   StopTimer(5200);
   fprintf(stdoutMPI, "%s", "######  End  : Diagonalization.  ######\n\n");
   if(iret != 0) return FALSE;
   X->Bind.Def.St=0;
   fprintf(stdoutMPI, "%s", "######  Start: Calc Expected value.  ######\n\n");
   StartTimer(5300);
   phys(&(X->Bind), X->Bind.Check.idim_max);
   StopTimer(5300);
   fprintf(stdoutMPI, "%s", "######  End  : Calc Expected value.  ######\n\n");
   StartTimer(5400);
   iret=output(&(X->Bind));
   StopTimer(5400);
   fprintf(stdoutMPI, "%s", "######  Finish Calculation.  ######\n");
   if(iret != 0) return FALSE;
   return TRUE;
 }