HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/CalcSpectrumByFullDiag.cpp File Reference
CalcSpectrumByFullDiag.cpp File Reference
Functions to perform spectrum calculations with the full-diagonalization method.
#include <complex>
#include "global.hpp"
#include <ctime>
#include "struct.hpp"
#include "lapack_diag.hpp"
#include "mltply.hpp"
#include "mltplyCommon.hpp"
#include "CalcTime.hpp"
#include "common/setmemory.hpp"
#include "CalcSpectrum.hpp"
Functions
int CalcSpectrumByFullDiag (struct EDMainCalStruct *X, int Nomega, int NdcSpectrum, std::complex< double > **dcSpectrum, std::complex< double > *dcomega, std::complex< double > **v1Org)
Compute the Green function with the Lehmann representation and FD
\[ G(z) = \sum_n \frac{|\langle n|c|0\rangle|^2}{z - E_n} \]
.
Detailed Description
Functions to perform spectrum calculations with the full-diagonalization method.
Definition in file CalcSpectrumByFullDiag.cpp.
Function Documentation
CalcSpectrumByFullDiag()
int CalcSpectrumByFullDiag (struct EDMainCalStruct * X, int Nomega, int NdcSpectrum, std::complex< double > ** dcSpectrum, std::complex< double > * dcomega, std::complex< double > ** v1Org)
Compute the Green function with the Lehmann representation and FD
\[ G(z) = \sum_n \frac{|\langle n|c|0\rangle|^2}{z - E_n} \]
.
Author
Mitsuaki Kawamura (The University of Tokyo)
Generate fully stored Hamiltonian. Because v0 & v1 are overwritten, copy v0 into ::vg.
v0 becomes eigenvalues in lapack_diag(), and v1 becomes eigenvectors
Compute \(|\langle n|c|0\rangle|^2\) for all \(n\) and store them into v1, where \(c|0\rangle\) is ::vg.
Compute spectrum
\[ \sum_n \frac{|\langle n|c|0\rangle|^2}{z - E_n} \]
Parameters
[in,out] X
[in] Nomega Number of frequencies
[out] dcSpectrum [Nomega] Spectrum
[in] dcomega [Nomega] Frequency
Definition at line 37 of file CalcSpectrumByFullDiag.cpp.
References EDMainCalStruct::Bind, BindStruct::Check, PhysList::energy, GetExcitedState(), CheckList::idim_max, lapack_diag(), mltply(), BindStruct::Phys, StartTimer(), StopTimer(), v0, v1, and zclear().
Referenced by CalcSpectrum().
 {
   int idim, jdim, iomega, idim_max_int, idcSpectrum;
   std::complex<double> **vR, **vL, vRv, vLv, *vLvvRv;
   idim_max_int = (int)X->Bind.Check.idim_max;
   vR = cd_2d_allocate(idim_max_int, 1);
   vL = cd_2d_allocate(idim_max_int, 1);
   vLvvRv = cd_1d_allocate(idim_max_int);
   StartTimer(6301);
   zclear((X->Bind.Check.idim_max + 1)*(X->Bind.Check.idim_max + 1), &v0[0][0]);
   zclear((X->Bind.Check.idim_max + 1)*(X->Bind.Check.idim_max + 1), &v1[0][0]);
   for (idim = 1; idim <= X->Bind.Check.idim_max; idim++) v1[idim][idim] = 1.0;
   mltply(&(X->Bind), X->Bind.Check.idim_max, v0, v1);
   StopTimer(6301);
   StartTimer(6302);
   lapack_diag(&(X->Bind));
   StopTimer(6302);
   zclear(X->Bind.Check.idim_max, &vR[1][0]);
   GetExcitedState(&(X->Bind), 1, vR, v1Org, 0);
   for (idcSpectrum = 0; idcSpectrum < NdcSpectrum; idcSpectrum++) {
     StartTimer(6303);
     zclear(X->Bind.Check.idim_max, &vL[1][0]);
     GetExcitedState(&(X->Bind), 1, vL, v1Org, idcSpectrum + 1);
     for (idim = 0; idim < idim_max_int; idim++) {
       vRv = 0.0;
       vLv = 0.0;
       for (jdim = 0; jdim < idim_max_int; jdim++) {
         vRv += conj(v1[jdim][idim]) * vR[jdim][1];
         vLv += conj(v1[jdim][idim]) * vL[jdim][1];
       }
       vLvvRv[idim] = conj(vLv) * vRv;
     }/*for (idim = 0; idim < idim_max_int; idim++)*/
     StopTimer(6303);
     StartTimer(6304);
     for (iomega = 0; iomega < Nomega; iomega++) {
       dcSpectrum[iomega][idcSpectrum] = 0.0;
       for (idim = 0; idim < idim_max_int; idim++) {
         dcSpectrum[iomega][idcSpectrum] += vLvvRv[idim] / (dcomega[iomega] - X->Bind.Phys.energy[idim]);
       }/*for (idim = 0; idim < idim_max_int; idim++)*/
     }/*for (iomega = 0; iomega < Nomega; iomega++)*/
     StopTimer(6304);
   }/*for (idcSpectrum = 1; idcSpectrum < NdcSpectrum; idcSpectrum++)*/
   free_cd_2d_allocate(vL);
   free_cd_2d_allocate(vR);
   free_cd_1d_allocate(vLvvRv);
   return TRUE;
 }/*CalcSpectrumByFullDiag*/