HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/Multiply.cpp File Reference
Multiply.cpp File Reference
File for giving multiplying functions to the wave vectors for TPQ and TE method.
#include "Common.hpp"
#include "diagonalcalc.hpp"
#include "Multiply.hpp"
#include "wrapperMPI.hpp"
#include "mltply.hpp"
#include <iostream>
Functions
int Multiply (struct BindStruct *X)
Function of calculating the i-th step norm as
\[ N^{(i)} = |L v_1^{(i)}-v_0^{(i)}/N_s | \]
and update the i+1-th wave vector as
\[ v_0^{(i+1)} = \frac{L v_1^{(i)}-v_0^{(i)}/N_s}{N^{(i)}} \]
for TPQ calculation.
int MultiplyForTEM (struct BindStruct *X, std::complex< double > **v2)
Function of multiplying Hamiltonian for Time Evolution.
Detailed Description
File for giving multiplying functions to the wave vectors for TPQ and TE method.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Kota Ido (The University of Tokyo)
Definition in file Multiply.cpp.
Function Documentation
Multiply()
int Multiply (struct BindStruct * X)
Function of calculating the i-th step norm as
\[ N^{(i)} = |L v_1^{(i)}-v_0^{(i)}/N_s | \]
and update the i+1-th wave vector as
\[ v_0^{(i+1)} = \frac{L v_1^{(i)}-v_0^{(i)}/N_s}{N^{(i)}} \]
for TPQ calculation.
Parameters
X [in] data list for calculation (idim_max and NsiteMPI)
Return values
0 normally finished
-1 unnormally finished
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition at line 44 of file Multiply.cpp.
References BindStruct::Check, BindStruct::Def, global_norm, CheckList::idim_max, LargeValue, MultiplyForTEM(), NormMPI_dv(), DefineList::NsiteMPI, NumAve, v0, and v1.
Referenced by CalcByTPQ().
 {
   long int i, i_max;
   double Ns;
   int rand_i;
   i_max = X->Check.idim_max;
   Ns = 1.0*X->Def.NsiteMPI;
   // mltply is in expec_energy.cpp v0=H*v1
 #pragma omp parallel for default(none) private(i,rand_i)  \
   shared(v0, v1,NumAve) firstprivate(i_max, Ns, LargeValue)
   for (i = 1; i <= i_max; i++) {
     for (rand_i = 0; rand_i < NumAve; rand_i++) {
       v0[i][rand_i] = LargeValue * v1[i][rand_i] - v0[i][rand_i] / Ns;  //v0=(l-H/Ns)*v1
     }
   }
   NormMPI_dv(i_max, NumAve, v0, global_norm);
 #pragma omp parallel for default(none) private(i,rand_i) \
 shared(v0,NumAve,global_norm) firstprivate(i_max)
   for (i = 1; i <= i_max; i++)
     for (rand_i = 0; rand_i < NumAve; rand_i++)
       v0[i][rand_i] = v0[i][rand_i] / global_norm[rand_i];
   return 0;
 }
MultiplyForTEM()
int MultiplyForTEM (struct BindStruct * X, std::complex< double > ** v2)
Function of multiplying Hamiltonian for Time Evolution.
Make \(|v_0 \rangle = |\psi(t+dt) \rangle \) from \(|v_1 \rangle = | \psi(t) \rangle \) and \(|v_0 \rangle = H |\psi(t) \rangle \).
Parameters
X [in] data list for calculation (idim_max and TimeSlice)
Return values
0 normally finished
-1 unnormally finished
Definition at line 80 of file Multiply.cpp.
References BindStruct::Check, BindStruct::Def, ParamList::ExpandCoef, global_norm, I(), CheckList::idim_max, mltply(), DefineList::Param, SumMPI_d(), ParamList::TimeSlice, v0, and v1.
Referenced by CalcByTEM(), and Multiply().
 {
   long int i, i_max;
   int coef;
   double dnorm = 0.0;
   std::complex<double> tmp1 = 1.0;
   std::complex<double> tmp2 = 0.0;
   double dt = X->Def.Param.TimeSlice;
   //Make |v0> = |psi(t+dt)> from |v1> = |psi(t)> and |v0> = H |psi(t)>
   i_max = X->Check.idim_max;
   // mltply is in expec_energy.cpp v0=H*v1
   if (dt < pow(10.0, -14)) {
 #pragma omp parallel for default(none) private(i) \
 shared(I,v0, v1, v2) firstprivate(i_max, dt, tmp2)
     for (i = 1; i <= i_max; i++) {
       tmp2 = v0[i][0];
       v0[i][0] = v1[i][0];  //v0=(1-i*dt*H)*v1
       v1[i][0] = tmp2;
       v2[i][0] = 0.0 + I * 0.0;
     }
     mltply(X, 1, v2, v1);
   }
   else {
     tmp1 *= -I * dt;
 #pragma omp parallel for default(none) private(i) \
 shared(v0, v1, v2,I) firstprivate(i_max, dt, tmp1, tmp2)
     for (i = 1; i <= i_max; i++) {
       tmp2 = v0[i][0];
       v0[i][0] = v1[i][0] + tmp1 * tmp2;  //v0=(1-i*dt*H)*v1
       v1[i][0] = tmp2;
       v2[i][0] = 0.0 + I * 0.0;
     }
     for (coef = 2; coef <= X->Def.Param.ExpandCoef; coef++) {
       tmp1 *= -I * dt / (std::complex<double>)coef;
       //v2 = H*v1 = H^coef |psi(t)>
       mltply(X, 1, v2, v1);
 #pragma omp parallel for default(none) private(i) shared(I, v0, v1, v2) \
 firstprivate(i_max, tmp1, myrank)
       for (i = 1; i <= i_max; i++) {
         v0[i][0] += tmp1 * v2[i][0];
         v1[i][0] = v2[i][0];
         v2[i][0] = 0.0 + I * 0.0;
       }
     }
   }
   dnorm = 0.0;
 #pragma omp parallel for default(none) reduction(+: dnorm) private(i) shared(v0) \
 firstprivate(i_max, dt)
   for (i = 1; i <= i_max; i++) {
     dnorm += real(conj(v0[i][0])*v0[i][0]);
   }
   dnorm = SumMPI_d(dnorm);
   dnorm = sqrt(dnorm);
   global_norm[0] = dnorm;
 #pragma omp parallel for default(none) private(i) shared(v0) firstprivate(i_max, dnorm)
   for (i = 1; i <= i_max; i++) {
     v0[i][0] = v0[i][0] / dnorm;
   }
   return 0;
 }