HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/PairEx.cpp File Reference
PairEx.cpp File Reference
Calculating the pair excited state generated by the pair operator
\[ \sum_{i,j, \sigma_1, \sigma_2} h_{i,\sigma_1, j, \sigma_2} c_{i\sigma_1} c_{j\sigma_2} (a_{i\sigma_1} a_{j\sigma_2})\]
, where \(c_{i\sigma_1} (a_{i\sigma_1})\) indicates a creation (anti-creation) operator at \(i\)-th site with \(\sigma_1 \) spin.
#include "bitcalc.hpp"
#include "mltplyCommon.hpp"
#include "PairEx.hpp"
#include "PairExHubbard.hpp"
#include "PairExSpin.hpp"
Functions
int GetPairExcitedState (struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, int iEx)
Calculating the pair excited state by the pair operator;
\[ \sum_{i,j, \sigma_1, \sigma_2} h_{i,\sigma_1, j, \sigma_2} c_{i\sigma_1} c_{j\sigma_2} (a_{i\sigma_1} a_{j\sigma_2})\]
, where \(c_{i\sigma_1} (a_{i\sigma_1})\) indicates a creation (anti-creation) operator at \(i\)-th site with \(\sigma_1 \) spin. Target System: Hubbard, Kondo, Spin.
Detailed Description
Calculating the pair excited state generated by the pair operator
\[ \sum_{i,j, \sigma_1, \sigma_2} h_{i,\sigma_1, j, \sigma_2} c_{i\sigma_1} c_{j\sigma_2} (a_{i\sigma_1} a_{j\sigma_2})\]
, where \(c_{i\sigma_1} (a_{i\sigma_1})\) indicates a creation (anti-creation) operator at \(i\)-th site with \(\sigma_1 \) spin.
Version
1.2
Author
Kazuyoshi Yoshimi (The University of Tokyo)
Definition in file PairEx.cpp.
Function Documentation
GetPairExcitedState()
int GetPairExcitedState (struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, int iEx)
Calculating the pair excited state by the pair operator;
\[ \sum_{i,j, \sigma_1, \sigma_2} h_{i,\sigma_1, j, \sigma_2} c_{i\sigma_1} c_{j\sigma_2} (a_{i\sigma_1} a_{j\sigma_2})\]
, where \(c_{i\sigma_1} (a_{i\sigma_1})\) indicates a creation (anti-creation) operator at \(i\)-th site with \(\sigma_1 \) spin. Target System: Hubbard, Kondo, Spin.
Parameters
X [in] define list to get and put information of calculation
tmp_v0 [in, out] Result \(v_0 += H v_1 \).
tmp_v1 [in] The wave vector \(v_1 \) to be mltiplied by the Hamiltonian \(H v_1 \).
Returns
TRUE: Normally finished
FALSE: Unnormally finished
Author
Kazuyoshi Yoshimi (The University of Tokyo)
Version
1.2
Definition at line 47 of file PairEx.cpp.
References BindStruct::Check, BindStruct::Def, GetPairExcitedStateHubbard(), GetPairExcitedStateHubbardGC(), GetPairExcitedStateSpin(), GetPairExcitedStateSpinGC(), GetSplitBitByModel(), GetSplitBitForGeneralSpin(), LargeList::i_max, DefineList::iCalcModel, CheckList::idim_maxOrg, DefineList::iFlgGeneralSpin, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, LargeList::mode, DefineList::Nsite, and DefineList::SiteToBit.
Referenced by GetExcitedState().
 {
   int iret;
   long int irght, ilft, ihfbit;
   //  i_max = X->Check.idim_max;
   if (X->Def.iFlgGeneralSpin == FALSE) {
     if (GetSplitBitByModel(X->Def.Nsite, X->Def.iCalcModel, &irght, &ilft, &ihfbit) != 0) {
       return -1;
     }
   }
   else {
     if (GetSplitBitForGeneralSpin(X->Def.Nsite, &ihfbit, X->Def.SiteToBit) != 0) {
       return -1;
     }
   }
   X->Large.i_max = X->Check.idim_maxOrg;
   X->Large.irght = irght;
   X->Large.ilft = ilft;
   X->Large.ihfbit = ihfbit;
   X->Large.mode = M_CALCSPEC;
   switch (X->Def.iCalcModel) {
   case HubbardGC:
     iret = GetPairExcitedStateHubbardGC(X, nstate, tmp_v0, tmp_v1, iEx);
     break;
   case KondoGC:
   case Hubbard:
   case Kondo:
     iret = GetPairExcitedStateHubbard(X, nstate, tmp_v0, tmp_v1, iEx);
     break;
   case Spin: // for the Sz-conserved spin system
     iret = GetPairExcitedStateSpin(X, nstate, tmp_v0, tmp_v1, iEx);
     break;
   case SpinGC:
     iret = GetPairExcitedStateSpinGC(X, nstate, tmp_v0, tmp_v1, iEx);
     break;
   default:
     iret = FALSE;
     break;
   }
   return iret;
 }