HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/StdFace/TriangularLattice.cpp File Reference
TriangularLattice.cpp File Reference
Standard mode for the triangular lattice.
#include "StdFace_vals.hpp"
#include "StdFace_ModelUtil.hpp"
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <complex>
#include <cstring>
Functions
void StdFace_Triangular (struct StdIntList *StdI)
Setup a Hamiltonian for the Triangular lattice.
Detailed Description
Standard mode for the triangular lattice.
Definition in file TriangularLattice.cpp.
Function Documentation
StdFace_Triangular()
void StdFace_Triangular (struct StdIntList * StdI)
Setup a Hamiltonian for the Triangular lattice.
Author
Mitsuaki Kawamura (The University of Tokyo)
(1) Compute the shape of the super-cell and sites in the super-cell
(2) check & store parameters of Hamiltonian
(3) Set local spin flag (StdIntList::locspinflag) and the number of sites (StdIntList::nsite)
(4) Compute the upper limit of the number of Transfer & Interaction and malloc them.
(5) Set Transfer & Interaction
Definition at line 33 of file TriangularLattice.cpp.
References StdFace_Coulomb(), StdFace_GeneralJ(), StdFace_Hopping(), StdFace_HubbardLocal(), StdFace_InitSite(), StdFace_InputCoulombV(), StdFace_InputHopp(), StdFace_InputSpin(), StdFace_InputSpinNN(), StdFace_MagField(), StdFace_MallocInteractions(), StdFace_NotUsed_c(), StdFace_NotUsed_d(), StdFace_NotUsed_i(), StdFace_NotUsed_J(), StdFace_PrintGeometry(), StdFace_PrintVal_d(), StdFace_PrintVal_i(), and StdFace_SetLabel().
Referenced by StdFace_main().
 {
   int isite, jsite, kCell, ntransMax, nintrMax;
   int iL, iW;
   FILE *fp;
   std::complex<double> Cphase;
   double dR[3];
   fp = fopen("lattice.gp", "w");
   StdI->NsiteUC = 1;
   fprintf(stdout, "  @ Lattice Size & Shape\n\n");
   StdFace_PrintVal_d("a", &StdI->a, 1.0);
   StdFace_PrintVal_d("Wlength", &StdI->length[0], StdI->a);
   StdFace_PrintVal_d("Llength", &StdI->length[1], StdI->a);
   StdFace_PrintVal_d("Wx", &StdI->direct[0][0], StdI->length[0]);
   StdFace_PrintVal_d("Wy", &StdI->direct[0][1], 0.0);
   StdFace_PrintVal_d("Lx", &StdI->direct[1][0], StdI->length[1] * 0.5);
   StdFace_PrintVal_d("Ly", &StdI->direct[1][1], StdI->length[1] * 0.5 * sqrt(3.0));
   StdFace_PrintVal_d("phase0", &StdI->phase[0], 0.0);
   StdFace_PrintVal_d("phase1", &StdI->phase[1], 0.0);
   StdFace_InitSite(StdI, fp, 2);
   StdI->tau[0][0] = 0.0; StdI->tau[0][1] = 0.0; StdI->tau[0][2] = 0.0;
   fprintf(stdout, "\n  @ Hamiltonian \n\n");
   StdFace_NotUsed_d("K", StdI->K);
   StdFace_PrintVal_d("h", &StdI->h, 0.0);
   StdFace_PrintVal_d("Gamma", &StdI->Gamma, 0.0);
   if (strcmp(StdI->model, "spin") == 0 ) {
     StdFace_PrintVal_i("2S", &StdI->S2, 1);
     StdFace_PrintVal_d("D", &StdI->D[2][2], 0.0);
     StdFace_InputSpinNN(StdI->J, StdI->JAll, StdI->J0, StdI->J0All, "J0");
     StdFace_InputSpinNN(StdI->J, StdI->JAll, StdI->J1, StdI->J1All, "J1");
     StdFace_InputSpinNN(StdI->J, StdI->JAll, StdI->J2, StdI->J2All, "J2");
     StdFace_InputSpinNN(StdI->Jp, StdI->JpAll, StdI->J0p, StdI->J0pAll, "J0'");
     StdFace_InputSpinNN(StdI->Jp, StdI->JpAll, StdI->J1p, StdI->J1pAll, "J1'");
     StdFace_InputSpinNN(StdI->Jp, StdI->JpAll, StdI->J2p, StdI->J2pAll, "J2'");
     StdFace_InputSpinNN(StdI->Jpp, StdI->JppAll, StdI->J0pp, StdI->J0ppAll, "J0'");
     StdFace_InputSpinNN(StdI->Jpp, StdI->JppAll, StdI->J1pp, StdI->J1ppAll, "J1'");
     StdFace_InputSpinNN(StdI->Jpp, StdI->JppAll, StdI->J2pp, StdI->J2ppAll, "J2'");
     StdFace_NotUsed_d("mu", StdI->mu);
     StdFace_NotUsed_d("U", StdI->U);
     StdFace_NotUsed_c("t", StdI->t);
     StdFace_NotUsed_c("t0", StdI->t0);
     StdFace_NotUsed_c("t1", StdI->t1);
     StdFace_NotUsed_c("t2", StdI->t2);
     StdFace_NotUsed_c("t'", StdI->tp);
     StdFace_NotUsed_c("t0'", StdI->t0p);
     StdFace_NotUsed_c("t1'", StdI->t1p);
     StdFace_NotUsed_c("t2'", StdI->t2p);
     StdFace_NotUsed_c("t''", StdI->tp);
     StdFace_NotUsed_c("t0''", StdI->t0pp);
     StdFace_NotUsed_c("t1''", StdI->t1pp);
     StdFace_NotUsed_c("t2''", StdI->t2pp);
     StdFace_NotUsed_d("V", StdI->V);
     StdFace_NotUsed_d("V0", StdI->V0);
     StdFace_NotUsed_d("V1", StdI->V1);
     StdFace_NotUsed_d("V2", StdI->V2);
     StdFace_NotUsed_d("V'", StdI->Vp);
     StdFace_NotUsed_d("V0'", StdI->V0p);
     StdFace_NotUsed_d("V1'", StdI->V1p);
     StdFace_NotUsed_d("V2'", StdI->V2p);
     StdFace_NotUsed_d("V''", StdI->Vpp);
     StdFace_NotUsed_d("V0''", StdI->V0pp);
     StdFace_NotUsed_d("V1''", StdI->V1pp);
     StdFace_NotUsed_d("V2''", StdI->V2pp);
   }/*if (strcmp(StdI->model, "spin") == 0 )*/
   else {
     StdFace_PrintVal_d("mu", &StdI->mu, 0.0);
     StdFace_PrintVal_d("U", &StdI->U, 0.0);
     StdFace_InputHopp(StdI->t, &StdI->t0, "t0");
     StdFace_InputHopp(StdI->t, &StdI->t1, "t1");
     StdFace_InputHopp(StdI->t, &StdI->t2, "t2");
     StdFace_InputHopp(StdI->tp, &StdI->t0p, "t0'");
     StdFace_InputHopp(StdI->tp, &StdI->t1p, "t1'");
     StdFace_InputHopp(StdI->tp, &StdI->t2p, "t2'");
     StdFace_InputHopp(StdI->tpp, &StdI->t0pp, "t0''");
     StdFace_InputHopp(StdI->tpp, &StdI->t1pp, "t1''");
     StdFace_InputHopp(StdI->tpp, &StdI->t2pp, "t2''");
     StdFace_InputCoulombV(StdI->V, &StdI->V0, "V0");
     StdFace_InputCoulombV(StdI->V, &StdI->V1, "V1");
     StdFace_InputCoulombV(StdI->V, &StdI->V2, "V2");
     StdFace_InputCoulombV(StdI->Vp, &StdI->V0p, "V0'");
     StdFace_InputCoulombV(StdI->Vp, &StdI->V1p, "V1'");
     StdFace_InputCoulombV(StdI->Vp, &StdI->V2p, "V2'");
     StdFace_InputCoulombV(StdI->Vpp, &StdI->V0pp, "V0''");
     StdFace_InputCoulombV(StdI->Vpp, &StdI->V1pp, "V1''");
     StdFace_InputCoulombV(StdI->Vpp, &StdI->V2pp, "V2''");
     StdFace_NotUsed_J("J0", StdI->J0All, StdI->J0);
     StdFace_NotUsed_J("J1", StdI->J1All, StdI->J1);
     StdFace_NotUsed_J("J2", StdI->J2All, StdI->J2);
     StdFace_NotUsed_J("J0'", StdI->J0pAll, StdI->J0p);
     StdFace_NotUsed_J("J1'", StdI->J1pAll, StdI->J1p);
     StdFace_NotUsed_J("J2'", StdI->J2pAll, StdI->J2p);
     StdFace_NotUsed_J("J0''", StdI->J0ppAll, StdI->J0pp);
     StdFace_NotUsed_J("J1''", StdI->J1ppAll, StdI->J1pp);
     StdFace_NotUsed_J("J2''", StdI->J2ppAll, StdI->J2pp);
     StdFace_NotUsed_d("D", StdI->D[2][2]);
     if (strcmp(StdI->model, "hubbard") == 0 ) {
       StdFace_NotUsed_i("2S", StdI->S2);
       StdFace_NotUsed_J("J", StdI->JAll, StdI->J);
     }/*if (strcmp(StdI->model, "hubbard") == 0 )*/
     else {
       StdFace_PrintVal_i("2S", &StdI->S2, 1);
       StdFace_InputSpin(StdI->J, StdI->JAll, "J");
     }/*if (model != "hubbard")*/
   }/*if (model != "spin")*/
   fprintf(stdout, "\n  @ Numerical conditions\n\n");
   StdI->nsite = StdI->NsiteUC * StdI->NCell;
   if (strcmp(StdI->model, "kondo") == 0 ) StdI->nsite *= 2;
   StdI->locspinflag = (int *)malloc(sizeof(int) * StdI->nsite);
   if (strcmp(StdI->model, "spin") == 0 )
     for (isite = 0; isite < StdI->nsite; isite++) StdI->locspinflag[isite] = StdI->S2;
   else if (strcmp(StdI->model, "hubbard") == 0 )
     for (isite = 0; isite < StdI->nsite; isite++) StdI->locspinflag[isite] = 0;
   else
     for (iL = 0; iL < StdI->nsite / 2; iL++) {
       StdI->locspinflag[iL] = StdI->S2;
       StdI->locspinflag[iL + StdI->nsite / 2] = 0;
     }
   if (strcmp(StdI->model, "spin") == 0 ) {
     ntransMax = StdI->nsite * (StdI->S2 + 1/*h*/ + 2 * StdI->S2/*Gamma*/);
     nintrMax = StdI->NCell * (StdI->NsiteUC/*D*/ + 3/*J*/ + 3/*J'*/ + 3/*J''*/)
       * (3 * StdI->S2 + 1) * (3 * StdI->S2 + 1);
   }
   else {
     ntransMax = StdI->NCell * 2/*spin*/ * (2 * StdI->NsiteUC/*mu+h+Gamma*/ + 6/*t*/ + 6/*t'*/ + 6/*t''*/);
     nintrMax = StdI->NCell * (StdI->NsiteUC/*U*/ + 4 * (3/*V*/ + 3/*V'*/ + 3/*V''*/));
     if (strcmp(StdI->model, "kondo") == 0) {
       ntransMax += StdI->nsite / 2 * (StdI->S2 + 1/*h*/ + 2 * StdI->S2/*Gamma*/);
       nintrMax += StdI->nsite / 2 * (3 * StdI->S2 + 1) * (3 * StdI->S2 + 1);
     }/*if (strcmp(StdI->model, "kondo") == 0)*/
   }
   StdFace_MallocInteractions(StdI, ntransMax, nintrMax);
   for (kCell = 0; kCell < StdI->NCell; kCell++) {
     iW = StdI->Cell[kCell][0];
     iL = StdI->Cell[kCell][1];
     /*
     Local term
     */
     isite = kCell;
     if (strcmp(StdI->model, "kondo") == 0 ) isite += StdI->NCell;
     if (strcmp(StdI->model, "spin") == 0 ) {
       StdFace_MagField(StdI, StdI->S2, -StdI->h, -StdI->Gamma, isite);
       StdFace_GeneralJ(StdI, StdI->D, StdI->S2, StdI->S2, isite, isite);
     }/*if (strcmp(StdI->model, "spin") == 0 )*/
     else {
       StdFace_HubbardLocal(StdI, StdI->mu, -StdI->h, -StdI->Gamma, StdI->U, isite);
       if (strcmp(StdI->model, "kondo") == 0 ) {
         jsite = kCell;
         StdFace_GeneralJ(StdI, StdI->J, 1, StdI->S2, isite, jsite);
         StdFace_MagField(StdI, StdI->S2, -StdI->h, -StdI->Gamma, jsite);
       }/*if (strcmp(StdI->model, "kondo") == 0 )*/
     }
     /*
     Nearest neighbor along W
     */
     StdFace_SetLabel(StdI, fp, iW, iL, 1, 0, 0, 0, &isite, &jsite, 1, &Cphase, dR);
     if (strcmp(StdI->model, "spin") == 0 ) {
       StdFace_GeneralJ(StdI, StdI->J0, StdI->S2, StdI->S2, isite, jsite);
     }/*if (strcmp(StdI->model, "spin") == 0 )*/
     else {
       StdFace_Hopping(StdI, Cphase * StdI->t0, isite, jsite, dR);
       StdFace_Coulomb(StdI, StdI->V0, isite, jsite);
     }
     /*
     Nearest neighbor along L
     */
     StdFace_SetLabel(StdI, fp, iW, iL, 0, 1, 0, 0, &isite, &jsite, 1, &Cphase, dR);
     if (strcmp(StdI->model, "spin") == 0 ) {
       StdFace_GeneralJ(StdI, StdI->J1, StdI->S2, StdI->S2, isite, jsite);
     }
     else {
       StdFace_Hopping(StdI, Cphase * StdI->t1, isite, jsite, dR);
       StdFace_Coulomb(StdI, StdI->V1, isite, jsite);
     }
     /*
     Nearest neighbor along W - L
     */
     StdFace_SetLabel(StdI, fp, iW, iL, 1, - 1, 0, 0, &isite, &jsite, 1, &Cphase, dR);
     if (strcmp(StdI->model, "spin") == 0 ) {
       StdFace_GeneralJ(StdI, StdI->J2, StdI->S2, StdI->S2, isite, jsite);
     }
     else {
       StdFace_Hopping(StdI, Cphase * StdI->t2, isite, jsite, dR);
       StdFace_Coulomb(StdI, StdI->V2, isite, jsite);
     }
     /*
     Second nearest neighbor 2W - L
     */
     StdFace_SetLabel(StdI, fp, iW, iL, 2, - 1, 0, 0, &isite, &jsite, 2, &Cphase, dR);
     if (strcmp(StdI->model, "spin") == 0 ) {
       StdFace_GeneralJ(StdI, StdI->J1p, StdI->S2, StdI->S2, isite, jsite);
     }/*if (strcmp(StdI->model, "spin") == 0 )*/
     else {
       StdFace_Hopping(StdI, Cphase * StdI->t1p, isite, jsite, dR);
       StdFace_Coulomb(StdI, StdI->V1p, isite, jsite);
     }
     /*
     Second nearest neighbor W+L
     */
     StdFace_SetLabel(StdI, fp, iW, iL, 1, 1, 0, 0, &isite, &jsite, 2, &Cphase, dR);
     if (strcmp(StdI->model, "spin") == 0 ) {
       StdFace_GeneralJ(StdI, StdI->J2p, StdI->S2, StdI->S2, isite, jsite);
     }/*if (strcmp(StdI->model, "spin") == 0 )*/
     else {
       StdFace_Hopping(StdI, Cphase * StdI->t2p, isite, jsite, dR);
       StdFace_Coulomb(StdI, StdI->V2p, isite, jsite);
     }/*if (model != "spin")*/
      /*
      Second nearest neighbor -W+2L
      */
     StdFace_SetLabel(StdI, fp, iW, iL, - 1, 2, 0, 0, &isite, &jsite, 2, &Cphase, dR);
     if (strcmp(StdI->model, "spin") == 0 ) {
       StdFace_GeneralJ(StdI, StdI->J0p, StdI->S2, StdI->S2, isite, jsite);
     }/*if (strcmp(StdI->model, "spin") == 0 )*/
     else {
       StdFace_Hopping(StdI, Cphase * StdI->t0p, isite, jsite, dR);
       StdFace_Coulomb(StdI, StdI->V0p, isite, jsite);
     }/*if (model != "spin")*/
     /*
     Third neighbor along 2W
     */
     StdFace_SetLabel(StdI, fp, iW, iL, 2, 0, 0, 0, &isite, &jsite, 3, &Cphase, dR);
     if (strcmp(StdI->model, "spin") == 0) {
       StdFace_GeneralJ(StdI, StdI->J0pp, StdI->S2, StdI->S2, isite, jsite);
     }/*if (strcmp(StdI->model, "spin") == 0 )*/
     else {
       StdFace_Hopping(StdI, Cphase * StdI->t0pp, isite, jsite, dR);
       StdFace_Coulomb(StdI, StdI->V0pp, isite, jsite);
     }
     /*
     Third neighbor along 2L
     */
     StdFace_SetLabel(StdI, fp, iW, iL, 0, 2, 0, 0, &isite, &jsite, 3, &Cphase, dR);
     if (strcmp(StdI->model, "spin") == 0) {
       StdFace_GeneralJ(StdI, StdI->J1pp, StdI->S2, StdI->S2, isite, jsite);
     }
     else {
       StdFace_Hopping(StdI, Cphase * StdI->t1pp, isite, jsite, dR);
       StdFace_Coulomb(StdI, StdI->V1pp, isite, jsite);
     }
     /*
     Nearest neighbor along 2W - 2L
     */
     StdFace_SetLabel(StdI, fp, iW, iL, 2, -2, 0, 0, &isite, &jsite, 3, &Cphase, dR);
     if (strcmp(StdI->model, "spin") == 0) {
       StdFace_GeneralJ(StdI, StdI->J2pp, StdI->S2, StdI->S2, isite, jsite);
     }
     else {
       StdFace_Hopping(StdI, Cphase * StdI->t2pp, isite, jsite, dR);
       StdFace_Coulomb(StdI, StdI->V2pp, isite, jsite);
     }
   }/*for (kCell = 0; kCell < StdI->NCell; kCell++)*/
   fprintf(fp, "plot \'-\' w d lc 7\n0.0 0.0\nend\npause -1\n");
   fclose(fp);
   StdFace_PrintGeometry(StdI);
 }