HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/input.cpp File Reference
input.cpp File Reference
#include "input.hpp"
#include "FileIO.hpp"
#include "wrapperMPI.hpp"
Functions
int inputHam (struct BindStruct *X)
Function Documentation
inputHam()
int inputHam (struct BindStruct * X)
Definition at line 20 of file input.cpp.
References DefineList::CDataFileHead, BindStruct::Check, childfopenMPI(), BindStruct::Def, fgetsMPI(), I(), CheckList::idim_max, stdoutMPI, and v0.
Referenced by CalcByFullDiag().
{
   //Input Ham
   long int i=0;
   long int ham_i=0;
   long int ham_j=0;
   long int imax = X->Check.idim_max;
   long int ihermite=0;
   long int itmp;
   double dHam_re, dHam_im;
   char ctmp[256], ctmp2[256];
   FILE *fp;
   char sdt[D_FileNameMax];
   sprintf(sdt,"%s_Ham.dat", X->Def.CDataFileHead);
   if(childfopenMPI(sdt,"r",&fp)!=0){
     return -1;
   }
   //skip: header
   fgetsMPI(ctmp, sizeof(ctmp) / sizeof(char), fp);
   //skip: read imax, imax, ihermite
   fgetsMPI(ctmp, sizeof(ctmp) / sizeof(char), fp);
   sscanf(ctmp, "%ld %ld %ld\n", &itmp, &itmp, &ihermite);
   if(itmp != imax){
     fprintf(stdoutMPI, "Error: The dimension of input Hamiltonian is wrong: input=%ld, idim=%ld.\n", itmp, imax);
     return -1;
   }
   for(i=1; i<= ihermite; i++){
     fgetsMPI(ctmp2, sizeof(ctmp2) / sizeof(char), fp);
     sscanf(ctmp2, "%ld %ld %lf %lf\n",
            &ham_i, &ham_j, &dHam_re, &dHam_im);
     v0[ham_i][ham_j]=dHam_re+I*dHam_im;
     v0[ham_j][ham_i]=conj(v0[ham_i][ham_j]);
   }
  fclose(fp);
  return 0;
 }