HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/mltplyMPIHubbard.cpp File Reference
mltplyMPIHubbard.cpp File Reference
Functions for Hubbard Hamiltonian + MPI.
#include "Common.hpp"
#include "bitcalc.hpp"
#include "wrapperMPI.hpp"
#include "mltplyCommon.hpp"
#include "mltplyMPIHubbard.hpp"
Functions
void GC_child_general_hopp_MPIdouble (long int itrans, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Hopping term in Hubbard + GC When both site1 and site2 are in the inter process region.
void X_GC_child_general_hopp_MPIdouble (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Hopping term in Hubbard + GC When both site1 and site2 are in the inter process region.
void X_child_CisAjt_MPIdouble (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Hopping term in Hubbard + MPI When both site1 and site2 are in the inter process region.
void GC_child_general_hopp_MPIsingle (long int itrans, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Hopping term in Hubbard + GC When only site2 is in the inter process region.
void X_GC_child_general_hopp_MPIsingle (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Hopping term in Hubbard + GC When only site2 is in the inter process region.
void child_general_hopp_MPIdouble (long int itrans, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Hopping term in Hubbard (Kondo) + Canonical ensemble When both site1 and site2 are in the inter process region.
void X_child_general_hopp_MPIdouble (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Hopping term in Hubbard (Kondo) + Canonical ensemble When both site1 and site2 are in the inter process region.
void child_general_hopp_MPIsingle (long int itrans, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Hopping term in Hubbard (Kondo) + Canonical ensemble When only site2 is in the inter process region.
void X_child_general_hopp_MPIsingle (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Hopping term in Hubbard (Kondo) + Canonical ensemble When only site2 is in the inter process region.
void X_child_CisAjt_MPIsingle (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Hopping term in Hubbard (Kondo) + Canonical ensemble When only site2 is in the inter process region.
Detailed Description
Functions for Hubbard Hamiltonian + MPI.
Definition in file mltplyMPIHubbard.cpp.
Function Documentation
child_general_hopp_MPIdouble()
void child_general_hopp_MPIdouble (long int itrans, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Hopping term in Hubbard (Kondo) + Canonical ensemble When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] itrans Transfer ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 236 of file mltplyMPIHubbard.cpp.
References BindStruct::Def, DefineList::EDGeneralTransfer, DefineList::EDParaGeneralTransfer, and X_child_general_hopp_MPIdouble().
Referenced by mltplyHubbard().
  {
   X_child_general_hopp_MPIdouble(
     X->Def.EDGeneralTransfer[itrans][0], X->Def.EDGeneralTransfer[itrans][1],
     X->Def.EDGeneralTransfer[itrans][2], X->Def.EDGeneralTransfer[itrans][3],
     X->Def.EDParaGeneralTransfer[itrans], X, nstate, tmp_v0, tmp_v1);
 }/*void child_general_hopp_MPIdouble*/
child_general_hopp_MPIsingle()
void child_general_hopp_MPIsingle (long int itrans, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Hopping term in Hubbard (Kondo) + Canonical ensemble When only site2 is in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] itrans Transfer ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 309 of file mltplyMPIHubbard.cpp.
References BindStruct::Def, DefineList::EDGeneralTransfer, DefineList::EDParaGeneralTransfer, and X_child_general_hopp_MPIsingle().
Referenced by mltplyHubbard().
  {
   X_child_general_hopp_MPIsingle(
     X->Def.EDGeneralTransfer[itrans][0], X->Def.EDGeneralTransfer[itrans][1],
     X->Def.EDGeneralTransfer[itrans][2], X->Def.EDGeneralTransfer[itrans][3],
     X->Def.EDParaGeneralTransfer[itrans], X, nstate, tmp_v0, tmp_v1);
 }/*void child_general_hopp_MPIsingle*/
GC_child_general_hopp_MPIdouble()
void GC_child_general_hopp_MPIdouble (long int itrans, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Hopping term in Hubbard + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] itrans Transfer ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 30 of file mltplyMPIHubbard.cpp.
References BindStruct::Def, DefineList::EDGeneralTransfer, DefineList::EDParaGeneralTransfer, and X_GC_child_general_hopp_MPIdouble().
Referenced by mltplyHubbardGC().
  {
   X_GC_child_general_hopp_MPIdouble(
     X->Def.EDGeneralTransfer[itrans][0], X->Def.EDGeneralTransfer[itrans][1],
     X->Def.EDGeneralTransfer[itrans][2], X->Def.EDGeneralTransfer[itrans][3],
     X->Def.EDParaGeneralTransfer[itrans], X, nstate, tmp_v0, tmp_v1);
 }/*void GC_child_general_hopp_MPIdouble*/
GC_child_general_hopp_MPIsingle()
void GC_child_general_hopp_MPIsingle (long int itrans, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Hopping term in Hubbard + GC When only site2 is in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] itrans Transfer ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 147 of file mltplyMPIHubbard.cpp.
References BindStruct::Def, DefineList::EDGeneralTransfer, DefineList::EDParaGeneralTransfer, and X_GC_child_general_hopp_MPIsingle().
Referenced by mltplyHubbardGC().
  {
   X_GC_child_general_hopp_MPIsingle(
     X->Def.EDGeneralTransfer[itrans][0], X->Def.EDGeneralTransfer[itrans][1],
     X->Def.EDGeneralTransfer[itrans][2], X->Def.EDGeneralTransfer[itrans][3],
     X->Def.EDParaGeneralTransfer[itrans], X, nstate, tmp_v0, tmp_v1       );
 }/*void GC_child_general_hopp_MPIsingle*/
X_child_CisAjt_MPIdouble()
void X_child_CisAjt_MPIdouble (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Hopping term in Hubbard + MPI When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Returns
fragment of \(\langle v_1|{\hat H}|v_1\rangle\)
Parameters
[in] org_isite1 \(i_1\) of \(c_{i_1 \sigma_1}^\dagger c_{i_2 \sigma_2}\)
[in] org_ispin1 \(\sigma_1\) of \(c_{i_1 \sigma_1}^\dagger c_{i_2 \sigma_2}\)
[in] org_isite2 \(i_2\) of \(c_{i_1 \sigma_1}^\dagger c_{i_2 \sigma_2}\)
[in] org_ispin2 \(\sigma_2\) of \(c_{i_1 \sigma_1}^\dagger c_{i_2 \sigma_2}\)
[in] tmp_trans Transfer \(t\)
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 92 of file mltplyMPIHubbard.cpp.
References BindStruct::Check, BindStruct::Def, GetOffComp(), CheckList::idim_maxOrg, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1_org, list_1buf_org, list_2_1, list_2_2, LargeList::mode, myrank, SendRecv_cv(), SendRecv_i(), SendRecv_iv(), SgnBit(), DefineList::Tpow, and v1buf.
Referenced by GetPairExcitedStateHubbard().
   {
   int mask1, mask2, state1, state2, origin, bitdiff, Fsgn;
   long int idim_max_buf, j, ioff;
   std::complex<double> trans;
   int one = 1;
   mask1 = (int) X->Def.Tpow[2 * org_isite1 + org_ispin1];
   mask2 = (int) X->Def.Tpow[2 * org_isite2 + org_ispin2];
   if (mask2 > mask1) bitdiff = mask2 - mask1 * 2;
   else bitdiff = mask1 - mask2 * 2;
   origin = myrank ^ (mask1 + mask2);
   state1 = origin & mask1;
   state2 = origin & mask2;
   SgnBit((long int) (origin & bitdiff), &Fsgn); // Fermion sign
   if (state1 == 0 && state2 == mask2) {
     trans = -(double) Fsgn * tmp_trans;
   }/*if (state1 == 0 && state2 == mask2)*/
   else if (state1 == mask1 && state2 == 0) {
     trans = -(double) Fsgn * conj(tmp_trans);
     if (X->Large.mode == M_CORR|| X->Large.mode == M_CALCSPEC) {
       trans = 0;
     }
   }/*if (state1 == mask1 && state2 == 0)*/
   else return;
   idim_max_buf = SendRecv_i(origin, X->Check.idim_maxOrg);
   SendRecv_iv(origin, X->Check.idim_maxOrg + 1, idim_max_buf + 1, list_1_org, list_1buf_org);
   SendRecv_cv(origin, X->Check.idim_maxOrg*nstate, idim_max_buf*nstate, &tmp_v1[1][0], &v1buf[1][0]);
 #pragma omp parallel for default(none) private(j, ioff) \
   firstprivate(idim_max_buf, trans, X, list_2_1, list_2_2, list_1buf_org) \
   shared(v1buf, tmp_v0,nstate,one)
   for (j = 1; j <= idim_max_buf; j++) {
     GetOffComp(list_2_1, list_2_2, list_1buf_org[j],
                X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
     zaxpy_(&nstate, &trans, &v1buf[j][0], &one, &tmp_v0[ioff][0], &one);
   }/*for (j = 1; j <= idim_max_buf; j++)*/
 }/*void child_CisAjt_MPIdouble*/
X_child_CisAjt_MPIsingle()
void X_child_CisAjt_MPIsingle (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Hopping term in Hubbard (Kondo) + Canonical ensemble When only site2 is in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] org_isite1 Site 1
[in] org_ispin1 Spin 1
[in] org_isite2 Site 2
[in] org_ispin2 Spin 2
[in] tmp_trans Hopping integral
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 398 of file mltplyMPIHubbard.cpp.
References BindStruct::Check, BindStruct::Def, GetOffComp(), CheckList::idim_maxOrg, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1_org, list_1buf_org, list_2_1, list_2_2, myrank, DefineList::Nsite, SendRecv_cv(), SendRecv_i(), SendRecv_iv(), SgnBit(), DefineList::Tpow, and v1buf.
Referenced by GetPairExcitedStateHubbard().
  {
   int mask2, state2, origin, bit2diff, Fsgn;
   long int mask1, state1, idim_max_buf, j, state1check, bit1diff, ioff, jreal;
   std::complex<double> trans, dmv;
   int one = 1;
   /*
     Prepare index in the inter PE
   */
   mask2 = (int)X->Def.Tpow[2 * org_isite2+org_ispin2];
   bit2diff = mask2 - 1;
   origin = myrank ^ mask2;
   state2 = origin & mask2;
   SgnBit((long int) (origin & bit2diff), &Fsgn); // Fermion sign
   idim_max_buf = SendRecv_i(origin, X->Check.idim_maxOrg);
   SendRecv_iv(origin, X->Check.idim_maxOrg + 1, idim_max_buf + 1, list_1_org, list_1buf_org);
   SendRecv_cv(origin, X->Check.idim_maxOrg*nstate, idim_max_buf*nstate, &tmp_v1[1][0], &v1buf[1][0]);
   /*
     Index in the intra PE
   */
   mask1 = X->Def.Tpow[2 * org_isite1 + org_ispin1];
   if (state2 == mask2) {
     trans = -(double) Fsgn * tmp_trans;
     state1check = 0;
   }
   else if (state2 == 0) {
     state1check = mask1;
     trans = -(double) Fsgn * conj(tmp_trans);
   }
   else return;
   bit1diff = X->Def.Tpow[2 * X->Def.Nsite - 1] * 2 - mask1 * 2;
 #pragma omp parallel for default(none) private(j,dmv,Fsgn,ioff,jreal,state1) \
   firstprivate(idim_max_buf,trans,X,mask1,state1check,bit1diff,list_2_1,list_2_2,list_1buf_org,list_1) \
   shared(v1buf, tmp_v0,nstate,one)
   for (j = 1; j <= idim_max_buf; j++) {
     jreal = list_1buf_org[j];
     state1 = jreal & mask1;
     if (state1 == state1check) {
       SgnBit(jreal & bit1diff, &Fsgn);
       GetOffComp(list_2_1, list_2_2, jreal ^ mask1,
         X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
       if (ioff != 0) {
         dmv = (double)Fsgn * trans;
         zaxpy_(&nstate, &dmv, &v1buf[j][0], &one, &tmp_v0[ioff][0], &one);
       }/*if(ioff !=0)*/
     }/*if (state1 == state1check)*/
   }/*for (j = 1; j <= idim_max_buf; j++)*/
 }/*std::complex<double> child_general_hopp_MPIsingle*/
X_child_general_hopp_MPIdouble()
void X_child_general_hopp_MPIdouble (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Hopping term in Hubbard (Kondo) + Canonical ensemble When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] org_isite1 Site 1
[in] org_ispin1 Spin 1
[in] org_isite2 Site 2
[in] org_ispin2 Spin 2
[in] tmp_trans Hopping integral
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 252 of file mltplyMPIHubbard.cpp.
References BindStruct::Check, BindStruct::Def, GetOffComp(), CheckList::idim_max, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_1buf, list_2_1, list_2_2, LargeList::mode, myrank, SendRecv_cv(), SendRecv_i(), SendRecv_iv(), SgnBit(), DefineList::Tpow, and v1buf.
Referenced by child_general_hopp_MPIdouble(), expec_cisajs_Hubbard(), and GetPairExcitedStateHubbard().
   {
   int mask1, mask2, state1, state2, origin, bitdiff, Fsgn;
   long int idim_max_buf, j, ioff;
   std::complex<double> trans;
   int one = 1;
   mask1 = (int) X->Def.Tpow[2 * org_isite1 + org_ispin1];
   mask2 = (int) X->Def.Tpow[2 * org_isite2 + org_ispin2];
   if (mask2 > mask1) bitdiff = mask2 - mask1 * 2;
   else bitdiff = mask1 - mask2 * 2;
   origin = myrank ^ (mask1 + mask2);
   state1 = origin & mask1;
   state2 = origin & mask2;
   SgnBit((long int) (origin & bitdiff), &Fsgn); // Fermion sign
   if (state1 == 0 && state2 == mask2) {
     trans = -(double) Fsgn * tmp_trans;
   }
   else if (state1 == mask1 && state2 == 0) {
     trans = -(double) Fsgn * conj(tmp_trans);
     if (X->Large.mode == M_CORR|| X->Large.mode == M_CALCSPEC) trans = 0;
   }
   else return;
   idim_max_buf = SendRecv_i(origin, X->Check.idim_max);
   SendRecv_iv(origin, X->Check.idim_max + 1, idim_max_buf + 1, list_1, list_1buf);
   SendRecv_cv(origin, X->Check.idim_max*nstate, idim_max_buf*nstate, &tmp_v1[1][0], &v1buf[1][0]);
 #pragma omp parallel default(none) private(j,Fsgn,ioff) \
   firstprivate(idim_max_buf,trans,X) \
   shared(list_2_1,list_2_2,list_1buf,v1buf,tmp_v1,tmp_v0,nstate,one)
   {
 #pragma omp for
     for (j = 1; j <= idim_max_buf; j++) {
       GetOffComp(list_2_1, list_2_2, list_1buf[j],
                  X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
       zaxpy_(&nstate, &trans, &v1buf[j][0], &one, &tmp_v0[ioff][0], &one);
     }/*for (j = 1; j <= idim_max_buf; j++)*/
   }/*End of parallel region*/
 }/*void child_general_hopp_MPIdouble*/
X_child_general_hopp_MPIsingle()
void X_child_general_hopp_MPIsingle (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Hopping term in Hubbard (Kondo) + Canonical ensemble When only site2 is in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] org_isite1 Site 1
[in] org_ispin1 Spin 1
[in] org_isite2 Site 2
[in] org_ispin2 Spin 2
[in] tmp_trans Hopping integral
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 325 of file mltplyMPIHubbard.cpp.
References BindStruct::Check, BindStruct::Def, GetOffComp(), CheckList::idim_max, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_1buf, list_2_1, list_2_2, LargeList::mode, myrank, DefineList::Nsite, SendRecv_cv(), SendRecv_i(), SendRecv_iv(), SgnBit(), DefineList::Tpow, and v1buf.
Referenced by child_general_hopp_MPIsingle(), expec_cisajs_Hubbard(), and GetPairExcitedStateHubbard().
   {
   int mask2, state2, origin, bit2diff, Fsgn;
   long int mask1, state1, idim_max_buf, j, state1check, bit1diff, ioff, jreal;
   std::complex<double> trans, dmv;
   int one = 1;
   /*
     Prepare index in the inter PE
   */
   mask2 = (int)X->Def.Tpow[2 * org_isite2+org_ispin2];
   bit2diff = mask2 - 1;
   origin = myrank ^ mask2;
   state2 = origin & mask2;
   SgnBit((long int) (origin & bit2diff), &Fsgn); // Fermion sign
   idim_max_buf = SendRecv_i(origin, X->Check.idim_max);
   SendRecv_iv(origin, X->Check.idim_max + 1, idim_max_buf + 1, list_1, list_1buf);
   SendRecv_cv(origin, X->Check.idim_max*nstate, idim_max_buf*nstate, &tmp_v1[1][0], &v1buf[1][0]);
   /*
     Index in the intra PE
   */
   mask1 = X->Def.Tpow[2 * org_isite1 + org_ispin1];
   if (state2 == mask2) {
     trans = -(double) Fsgn * tmp_trans;
     state1check = 0;
   }
   else if (state2 == 0) {
     state1check = mask1;
     trans = -(double) Fsgn * conj(tmp_trans);
     if (X->Large.mode == M_CORR|| X->Large.mode == M_CALCSPEC) {
       trans = 0;
     }
   }
   else return;
   bit1diff = X->Def.Tpow[2 * X->Def.Nsite - 1] * 2 - mask1 * 2;
 #pragma omp parallel default(none)  private(j,dmv,Fsgn,ioff,jreal,state1) \
   firstprivate(idim_max_buf,trans,X,mask1,state1check,bit1diff,myrank) \
   shared(list_1,list_2_1,list_2_2,list_1buf,v1buf,tmp_v1,tmp_v0,nstate,one)
   {
 #pragma omp for
     for (j = 1; j <= idim_max_buf; j++) {
       jreal = list_1buf[j];
       state1 = jreal & mask1;
       if (state1 == state1check) {
         SgnBit(jreal & bit1diff,&Fsgn);
         GetOffComp(list_2_1, list_2_2, jreal ^ mask1,
             X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
         dmv = (double)Fsgn * trans;
         zaxpy_(&nstate, &dmv, &v1buf[j][0], &one, &tmp_v0[ioff][0], &one);
       }/*if (state1 == state1check)*/
     }/*for (j = 1; j <= idim_max_buf; j++)*/
   }/*End of parallel region*/
 }/*std::complex<double> child_general_hopp_MPIsingle*/
X_GC_child_general_hopp_MPIdouble()
void X_GC_child_general_hopp_MPIdouble (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Hopping term in Hubbard + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Returns
fragment of \(\langle v_1|{\hat H}|v_1\rangle\)
Parameters
[in] org_isite1 \(i_1\) of \(c_{i_1 \sigma_1}^\dagger c_{i_2 \sigma_2}\)
[in] org_ispin1 \(\sigma_1\) of \(c_{i_1 \sigma_1}^\dagger c_{i_2 \sigma_2}\)
[in] org_isite2 \(i_2\) of \(c_{i_1 \sigma_1}^\dagger c_{i_2 \sigma_2}\)
[in] org_ispin2 \(\sigma_2\) of \(c_{i_1 \sigma_1}^\dagger c_{i_2 \sigma_2}\)
[in] tmp_trans Transfer \(t\)
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 47 of file mltplyMPIHubbard.cpp.
References BindStruct::Check, BindStruct::Def, CheckList::idim_max, BindStruct::Large, LargeList::mode, myrank, SendRecv_cv(), SendRecv_i(), SgnBit(), DefineList::Tpow, v1buf, and zaxpy_long().
Referenced by expec_cisajs_HubbardGC(), GC_child_general_hopp_MPIdouble(), GetPairExcitedStateHubbardGC(), and X_GC_child_CisAjt_Hubbard_MPI().
   {
   int mask1, mask2, state1, state2, origin, bitdiff, Fsgn;
   long int idim_max_buf;
   std::complex<double> trans;
   mask1 = (int)X->Def.Tpow[2 * org_isite1 + org_ispin1];
   mask2 = (int)X->Def.Tpow[2 * org_isite2 + org_ispin2];
   if (mask2 > mask1) bitdiff = mask2 - mask1 * 2;
   else bitdiff = mask1 - mask2 * 2;
   origin = myrank ^ (mask1 + mask2);
   state1 = origin & mask1;
   state2 = origin & mask2;
   SgnBit((long int) (origin & bitdiff), &Fsgn); // Fermion sign
   if (state1 == 0 && state2 == mask2) {
     trans = -(double)Fsgn * tmp_trans;
   }/*if (state1 == 0 && state2 == mask2)*/
   else if (state1 == mask1 && state2 == 0) {
     trans = -(double)Fsgn * conj(tmp_trans);
     if (X->Large.mode == M_CORR || X->Large.mode == M_CALCSPEC) trans = 0.0;
   }/*if (state1 == mask1 && state2 == 0)*/
   else return;
   idim_max_buf = SendRecv_i(origin, X->Check.idim_max);
   SendRecv_cv(origin, X->Check.idim_max*nstate, idim_max_buf*nstate, &tmp_v1[1][0], &v1buf[1][0]);
   zaxpy_long(X->Check.idim_max*nstate, trans, &v1buf[1][0], &tmp_v0[1][0]);
 }/*void GC_child_general_hopp_MPIdouble*/
X_GC_child_general_hopp_MPIsingle()
void X_GC_child_general_hopp_MPIsingle (int org_isite1, int org_ispin1, int org_isite2, int org_ispin2, std::complex< double > tmp_trans, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Hopping term in Hubbard + GC When only site2 is in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] org_isite1 Site 1
[in] org_ispin1 Spin 1
[in] org_isite2 Site 2
[in] org_ispin2 Spin 2
[in] tmp_trans Hopping integral
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 164 of file mltplyMPIHubbard.cpp.
References BindStruct::Check, BindStruct::Def, CheckList::idim_max, BindStruct::Large, LargeList::mode, myrank, DefineList::Nsite, SendRecv_cv(), SendRecv_i(), SgnBit(), DefineList::Tpow, and v1buf.
Referenced by expec_cisajs_HubbardGC(), GC_child_general_hopp_MPIsingle(), GetPairExcitedStateHubbardGC(), and X_GC_child_CisAjt_Hubbard_MPI().
   {
   int mask2, state1, state2, origin, bit2diff, Fsgn;
   long int idim_max_buf, j, mask1, state1check, bit1diff, ioff;
   std::complex<double> trans, dmv;
   int one = 1;
   /*
     Prepare index in the inter PE
   */
   mask2 = (int) X->Def.Tpow[2 * org_isite2 + org_ispin2];
   bit2diff = mask2 - 1;
   origin = myrank ^ mask2;
   state2 = origin & mask2;
   SgnBit((long int) (origin & bit2diff), &Fsgn); // Fermion sign
   idim_max_buf = SendRecv_i(origin, X->Check.idim_max);
   SendRecv_cv(origin, X->Check.idim_max*nstate, idim_max_buf*nstate, &tmp_v1[1][0], &v1buf[1][0]);
   /*
     Index in the intra PE
   */
   mask1 = X->Def.Tpow[2 * org_isite1 + org_ispin1];
   if (state2 == mask2) {
     trans = -(double) Fsgn * tmp_trans;
     state1check = 0;
   }/*if (state2 == mask2)*/
   else if (state2 == 0) {
     state1check = mask1;
     trans = -(double) Fsgn * conj(tmp_trans);
     if (X->Large.mode == M_CORR|| X->Large.mode == M_CALCSPEC) trans = 0;
   }/*if (state2 != mask2)*/
   else return;
   bit1diff = X->Def.Tpow[2 * X->Def.Nsite - 1] * 2 - mask1 * 2;
 #pragma omp parallel default(none)  private(j,dmv,state1,Fsgn,ioff) \
   firstprivate(idim_max_buf,trans,X,mask1,state1check,bit1diff) \
   shared(v1buf,tmp_v1,tmp_v0,nstate,one)
   {
 #pragma omp for
     for (j = 0; j < idim_max_buf; j++) {
       state1 = j & mask1;
       if (state1 == state1check) {
         SgnBit(j & bit1diff, &Fsgn);
         ioff = j ^ mask1;
         dmv = (double)Fsgn * trans;
         zaxpy_(&nstate, &dmv, &v1buf[j + 1][0], &one, &tmp_v0[ioff + 1][0], &one);
       }/*if (state1 == state1check)*/
     }/*for (j = 0; j < idim_max_buf; j++)*/
   }/*End of parallel region*/
 }/*void GC_child_general_hopp_MPIsingle*/