HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/mltply.cpp File Reference
mltply.cpp File Reference
Multiplying the wavefunction by the Hamiltonian. \(H v_1\).
#include <bitcalc.hpp>
#include "mltply.hpp"
#include "mltplySpin.hpp"
#include "mltplyHubbard.hpp"
#include "wrapperMPI.hpp"
#include "CalcTime.hpp"
#include "mltplyCommon.hpp"
#include "diagonalcalc.hpp"
Functions
int mltply (struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Parent function of multiplying the wavefunction by the Hamiltonian. \(H v_1\).
First, the calculation of diagonal term is done by using the list \(\verb|list_diaognal| \).
Next, the calculation of off-diagonal term is done.
.
void zaxpy_long (long int n, std::complex< double > a, std::complex< double > *x, std::complex< double > *y)
Wrapper of zaxpy.
void zclear (long int n, std::complex< double > *x)
clear std::complex<double> array.
Detailed Description
Multiplying the wavefunction by the Hamiltonian. \(H v_1\).
Version
0.2
add function to treat the case of generalspin
Version
0.1
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition in file mltply.cpp.
Function Documentation
mltply()
int mltply (struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Parent function of multiplying the wavefunction by the Hamiltonian. \(H v_1\).
First, the calculation of diagonal term is done by using the list \(\verb|list_diaognal| \).
Next, the calculation of off-diagonal term is done.
.
Note
If \(\verb|mode| \) in BindStruct X is \(\verb|M_CORR| \), the wave function is not updated. The expected values are only calculated.
Otherwise, the wavefunction \(v_0 \) is updated as \(v_0 += H v_1\).
Parameters
X [in] Struct for getting the information of the operators.
tmp_v0 [in, out]
tmp_v1 [in]
Returns
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition at line 56 of file mltply.cpp.
References BindStruct::Check, BindStruct::Def, diagonalcalcForTE(), GetSplitBitByModel(), GetSplitBitForGeneralSpin(), LargeList::i_max, DefineList::iCalcModel, DefineList::iCalcType, CheckList::idim_max, DefineList::iFlgGeneralSpin, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_Diagonal, mltplyHubbard(), mltplyHubbardGC(), mltplySpin(), mltplySpinGC(), LargeList::mode, DefineList::Nsite, DefineList::SiteToBit, StartTimer(), step_i, and StopTimer().
Referenced by CalcByFullDiag(), CalcSpectrumByBiCG(), CalcSpectrumByFullDiag(), expec_energy_flct(), LOBPCG_Main(), and MultiplyForTEM().
{
   int one = 1;
   long int j=0;
   long int irght=0;
   long int ilft=0;
   long int ihfbit=0;
   std::complex<double> dmv;
   long int i_max;
   StartTimer(1);
   i_max = X->Check.idim_max;
   if (X->Def.iFlgGeneralSpin == FALSE) {
     if (GetSplitBitByModel(X->Def.Nsite, X->Def.iCalcModel, &irght, &ilft, &ihfbit) != 0) {
       return -1;
     }
   }
   else {
     if (X->Def.iCalcModel == Spin) {
       if (GetSplitBitForGeneralSpin(X->Def.Nsite, &ihfbit, X->Def.SiteToBit) != 0) {
         return -1;
       }
     }
   }
   X->Large.i_max = i_max;
   X->Large.irght = irght;
   X->Large.ilft = ilft;
   X->Large.ihfbit = ihfbit;
   X->Large.mode = M_MLTPLY;
   StartTimer(100);
 #pragma omp parallel for default(none) private(dmv) \
   firstprivate(i_max) shared(tmp_v0, tmp_v1, list_Diagonal,one,nstate)
   for (j = 1; j <= i_max; j++) {
     dmv = list_Diagonal[j];
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[j][0], &one);
   }
   StopTimer(100);
   if (X->Def.iCalcType == TimeEvolution) diagonalcalcForTE(step_i, X, &tmp_v0[0][0], &tmp_v1[0][0]);
   switch (X->Def.iCalcModel) {
   case HubbardGC:
     mltplyHubbardGC(X, nstate, tmp_v0, tmp_v1);
     break;
   case KondoGC:
   case Hubbard:
   case Kondo:
     mltplyHubbard(X, nstate, tmp_v0, tmp_v1);
     break;
   case Spin:
     mltplySpin(X, nstate, tmp_v0, tmp_v1);
     break;
   case SpinGC:
     mltplySpinGC(X, nstate, tmp_v0, tmp_v1);
     break;
   default:
     return -1;
   }
   StopTimer(1);
   return 0;
 }
zaxpy_long()
void zaxpy_long (long int n, std::complex< double > a, std::complex< double > * x, std::complex< double > * y)
Wrapper of zaxpy.
Definition at line 128 of file mltply.cpp.
Referenced by expec_cisajs_Hubbard(), expec_cisajs_HubbardGC(), expec_cisajs_SpinGeneral(), expec_cisajs_SpinHalf(), expec_cisajscktalt_SpinHalf(), GetPairExcitedStateHubbard(), GetPairExcitedStateHubbardGC(), X_child_CisAis_Hubbard_MPI(), X_child_CisAisCjtAjt_Hubbard_MPI(), X_child_CisAisCjuAju_GeneralSpin_MPIdouble(), X_GC_Ajt_MPI(), X_GC_child_AisCis_GeneralSpin_MPIdouble(), X_GC_child_AisCis_spin_MPIdouble(), X_GC_child_CisAis_GeneralSpin_MPIdouble(), X_GC_child_CisAis_Hubbard_MPI(), X_GC_child_CisAis_spin_MPIdouble(), X_GC_child_CisAisCjtAjt_Hubbard_MPI(), X_GC_child_CisAisCjuAju_GeneralSpin_MPIdouble(), X_GC_child_CisAisCjuAjv_GeneralSpin_MPIdouble(), X_GC_child_CisAisCjuAjv_spin_MPIdouble(), X_GC_child_CisAit_GeneralSpin_MPIdouble(), X_GC_child_CisAit_spin_MPIdouble(), X_GC_child_CisAitCiuAiv_spin_MPIdouble(), X_GC_child_CisAitCjuAju_GeneralSpin_MPIdouble(), X_GC_child_CisAitCjuAju_spin_MPIdouble(), X_GC_child_CisAitCjuAjv_GeneralSpin_MPIdouble(), X_GC_child_CisAjtCkuAlv_Hubbard_MPI(), X_GC_child_general_hopp_MPIdouble(), and X_GC_Cis_MPI().
   {
   long int i;
 #pragma omp parallel for default(none) private(i) shared(n, a, x, y)
   for (i = 0; i < n; i++)
     y[i] += a * x[i];
 }
zclear()
void zclear (long int n, std::complex< double > * x)
clear std::complex<double> array.
Definition at line 143 of file mltply.cpp.
Referenced by CalcByFullDiag(), CalcSpectrumByBiCG(), CalcSpectrumByFullDiag(), expec_cisajs_Hubbard(), expec_cisajs_HubbardGC(), expec_cisajs_SpinGCGeneral(), expec_cisajs_SpinGCHalf(), expec_cisajs_SpinGeneral(), expec_cisajs_SpinHalf(), expec_cisajscktalt_Hubbard(), expec_cisajscktalt_HubbardGC(), expec_cisajscktalt_SpinGCGeneral(), expec_cisajscktalt_SpinGCHalf(), expec_cisajscktalt_SpinGeneral(), expec_cisajscktalt_SpinHalf(), and LOBPCG_Main().
   {
   long int i;
 #pragma omp parallel for default(none) private(i) shared(n, x)
   for (i = 0; i < n; i++)
     x[i] = 0.0;
 }