HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/mltplySpinCore.cpp File Reference
mltplySpinCore.cpp File Reference
Functions for spin Hamiltonian (Core)
#include <bitcalc.hpp>
#include "xsetmem.hpp"
#include "wrapperMPI.hpp"
#include "mltplyCommon.hpp"
#include "mltplySpinCore.hpp"
Functions
int child_exchange_spin_GetInfo (int iExchange, struct BindStruct *X)
Set parameters for the bit operation of spin-exchange term.
int child_pairlift_spin_GetInfo (int iPairLift, struct BindStruct *X)
Set parameters for the bit operation of spin-pairlift term.
int child_general_int_spin_GetInfo (struct BindStruct *X, long int isite1, long int isite2, long int sigma1, long int sigma2, long int sigma3, long int sigma4, std::complex< double > tmp_V)
Set parameters for the bit operation of spin-general interaction term.
int X_Spin_CisAit (long int j, struct BindStruct *X, long int is1_spin, long int sigma2, long int *tmp_off)
Compute index of final wavefunction by \(c_{is}^\dagger c_{it}\) term.
int X_Spin_CisAis (long int j, long int is1_spin, long int sigma1)
Compute the spin state with bit mask is1_spin.
int X_SpinGC_CisAis (long int j, long int is1_spin, long int sigma1)
Compute the grandcanonical spin state with bit mask is1_spin.
int X_SpinGC_CisAit (long int j, long int is1_spin, long int sigma2, long int *tmp_off)
Compute index of final wavefunction by \(c_{is}^\dagger c_{it}\) term (grandcanonical).
int X_child_exchange_spin_element (long int j, struct BindStruct *X, long int isA_up, long int isB_up, long int sigmaA, long int sigmaB, long int *tmp_off)
Compute index of final wavefunction associated to spin-exchange term.
void child_exchange_spin_element (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int *tmp_off)
Multiply Hamiltonian of exchange term of canonical spin system.
void GC_child_exchange_spin_element (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int *tmp_off)
Multiply Hamiltonian of exchange term of grandcanonical spin system.
void GC_child_pairlift_spin_element (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int *tmp_off)
Multiply Hamiltonian of pairlift term of grandcanonical spin system.
void child_CisAisCisAis_spin_element (long int j, long int isA_up, long int isB_up, long int org_sigma2, long int org_sigma4, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of canonical spsin system.
void GC_child_CisAisCisAis_spin_element (long int j, long int isA_up, long int isB_up, long int org_sigma2, long int org_sigma4, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of grandcanonical spsin system.
void GC_child_CisAisCitAiu_spin_element (long int j, long int org_sigma2, long int org_sigma4, long int isA_up, long int isB_up, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int *tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{it}^\dagger c_{iu}\) term of grandcanonical spsin system.
void GC_child_CisAitCiuAiu_spin_element (long int j, long int org_sigma2, long int org_sigma4, long int isA_up, long int isB_up, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int *tmp_off)
Compute \(c_{is}^\dagger c_{it} c_{iu}^\dagger c_{iu}\) term of grandcanonical spsin system.
void GC_child_CisAitCiuAiv_spin_element (long int j, long int org_sigma2, long int org_sigma4, long int isA_up, long int isB_up, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int *tmp_off_2)
Compute \(c_{is}^\dagger c_{it} c_{iu}^\dagger c_{iv}\) term of grandcanonical spsin system.
Detailed Description
Functions for spin Hamiltonian (Core)
Definition in file mltplySpinCore.cpp.
Function Documentation
child_CisAisCisAis_spin_element()
void child_CisAisCisAis_spin_element (long int j, long int isA_up, long int isB_up, long int org_sigma2, long int org_sigma4, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of canonical spsin system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] org_sigma2 Target for spin 1
[in] org_sigma4 Target for spin 2
[in] tmp_V Coupling constatnt
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
Definition at line 357 of file mltplySpinCore.cpp.
References X_Spin_CisAis().
Referenced by expec_cisajscktalt_SpinHalf().
   {
   int tmp_sgn;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_Spin_CisAis(j, isB_up, org_sigma4);
   tmp_sgn *= X_Spin_CisAis(j, isA_up, org_sigma2);
   dmv = (std::complex<double>)tmp_sgn * tmp_V;
   zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[j][0], &one);
 }/*std::complex<double> child_CisAisCisAis_spin_element*/
child_exchange_spin_element()
void child_exchange_spin_element (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int * tmp_off)
Multiply Hamiltonian of exchange term of canonical spin system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 266 of file mltplySpinCore.cpp.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, LargeList::isA_spin, BindStruct::Large, list_1, list_2_1, list_2_2, and LargeList::tmp_J.
Referenced by child_exchange_spin().
   {
   long int off;
   long int iexchg;
   long int is_up = X->Large.isA_spin;
   long int irght = X->Large.irght;
   long int ilft = X->Large.ilft;
   long int ihfbit = X->Large.ihfbit;
   std::complex<double> tmp_J = X->Large.tmp_J;
   long int ibit_tmp;
   int one = 1;
   ibit_tmp = (list_1[j] & is_up);
   if (ibit_tmp == 0 || ibit_tmp == is_up) {
     return;
   }
   else {
     iexchg = list_1[j] ^ is_up;
     GetOffComp(list_2_1, list_2_2, iexchg, irght, ilft, ihfbit, &off);
     *tmp_off = off;
     zaxpy_(&nstate, &tmp_J, &tmp_v1[j][0], &one, &tmp_v0[off][0], &one);
   }
 }/*std::complex<double> child_exchange_spin_element*/
child_exchange_spin_GetInfo()
int child_exchange_spin_GetInfo (int iExchange, struct BindStruct * X)
Set parameters for the bit operation of spin-exchange term.
Returns
Always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Set the exchange coupling constant (LargeList::tmp_J)
Set the bit mask for computing spin state of both site (LargeList::is1_up, LargeList::is2_up)
Set the bit mask for exchange 2 spins (LargeList::isA_spin)
Parameters
[in] iExchange Counter of exchange interaction
[in,out] X
Definition at line 35 of file mltplySpinCore.cpp.
References BindStruct::Def, DefineList::ExchangeCoupling, LargeList::is1_up, LargeList::is2_up, LargeList::isA_spin, BindStruct::Large, DefineList::ParaExchangeCoupling, LargeList::tmp_J, and DefineList::Tpow.
Referenced by mltplyHalfSpin(), and mltplyHalfSpinGC().
   {
   int isite1 = X->Def.ExchangeCoupling[iExchange][0] + 1;
   int isite2 = X->Def.ExchangeCoupling[iExchange][1] + 1;
   X->Large.tmp_J = X->Def.ParaExchangeCoupling[iExchange];
   X->Large.is1_up = X->Def.Tpow[isite1 - 1];
   X->Large.is2_up = X->Def.Tpow[isite2 - 1];
   X->Large.isA_spin = X->Large.is1_up + X->Large.is2_up;
   return 0;
 }/*int child_exchange_spin_GetInfo*/
child_general_int_spin_GetInfo()
int child_general_int_spin_GetInfo (struct BindStruct * X, long int isite1, long int isite2, long int sigma1, long int sigma2, long int sigma3, long int sigma4, std::complex< double > tmp_V)
Set parameters for the bit operation of spin-general interaction term.
Returns
Always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Set the pairlift coupling constant (LargeList::tmp_J)
Set the bit mask for computing spin state of both site (LargeList::is1_up, LargeList::is2_up)
Set the bit mask for general interaction (LargeList::is1_spin, LargeList::is2_spin, LargeList::is3_spin, LargeList::is4_spin)
Parameters
[in,out] X
[in] isite1 Site 1
[in] isite2 Site 2
[in] sigma1 Sigma 1, final state of site 1
[in] sigma2 Sigma 3, initial state of site 1
[in] sigma3 Sigma 3, final state of site 2
[in] sigma4 Sigma 4, initial state of site 2
[in] tmp_V General interaction constatnt
Definition at line 91 of file mltplySpinCore.cpp.
References BindStruct::Def, LargeList::is1_spin, LargeList::is1_up, LargeList::is2_spin, LargeList::is2_up, LargeList::is3_spin, LargeList::is4_spin, LargeList::isite1, LargeList::isite2, BindStruct::Large, LargeList::tmp_V, and DefineList::Tpow.
Referenced by mltplyHalfSpin(), and mltplyHalfSpinGC().
   {
   X->Large.tmp_V = tmp_V;
   X->Large.isite1 = isite1;
   X->Large.isite2 = isite2;
   X->Large.is1_up = X->Def.Tpow[isite1 - 1];
   X->Large.is2_up = X->Def.Tpow[isite2 - 1];
   X->Large.is1_spin = sigma1;
   X->Large.is2_spin = sigma2;
   X->Large.is3_spin = sigma3;
   X->Large.is4_spin = sigma4;
   return 0;
 }/*int child_general_int_spin_GetInfo*/
child_pairlift_spin_GetInfo()
int child_pairlift_spin_GetInfo (int iPairLift, struct BindStruct * X)
Set parameters for the bit operation of spin-pairlift term.
Returns
Always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Set the pairlift coupling constant (LargeList::tmp_J)
Set the bit mask for computing spin state of both site (LargeList::is1_up, LargeList::is2_up)
Set the bit mask for exchange 2 spins (LargeList::isA_spin)
Definition at line 63 of file mltplySpinCore.cpp.
References BindStruct::Def, LargeList::is1_up, LargeList::is2_up, LargeList::isA_spin, BindStruct::Large, DefineList::PairLiftCoupling, DefineList::ParaPairLiftCoupling, LargeList::tmp_J, and DefineList::Tpow.
Referenced by mltplyHalfSpinGC().
   {
   int isite1 = X->Def.PairLiftCoupling[iPairLift][0] + 1;
   int isite2 = X->Def.PairLiftCoupling[iPairLift][1] + 1;
   X->Large.tmp_J = X->Def.ParaPairLiftCoupling[iPairLift];
   X->Large.is1_up = X->Def.Tpow[isite1 - 1];
   X->Large.is2_up = X->Def.Tpow[isite2 - 1];
   X->Large.isA_spin = X->Large.is1_up + X->Large.is2_up;
   return 0;
 }/*int child_pairlift_spin_GetInfo*/
GC_child_CisAisCisAis_spin_element()
void GC_child_CisAisCisAis_spin_element (long int j, long int isA_up, long int isB_up, long int org_sigma2, long int org_sigma4, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of grandcanonical spsin system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] org_sigma2 Target for spin 1
[in] org_sigma4 Target for spin 2
[in] tmp_V Coupling constatnt
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
Definition at line 386 of file mltplySpinCore.cpp.
References X_SpinGC_CisAis().
Referenced by expec_cisajscktalt_SpinGCHalf(), and GC_child_general_int_spin().
   {
   int tmp_sgn;
   std::complex<double> dmv = 0;
   int one = 1;
   tmp_sgn = X_SpinGC_CisAis(j, isB_up, org_sigma4);
   tmp_sgn *= X_SpinGC_CisAis(j, isA_up, org_sigma2);
   if (tmp_sgn != 0) {
     dmv = (std::complex<double>)tmp_sgn * tmp_V;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[j][0], &one);
   }
 }/*std::complex<double> GC_child_CisAisCisAis_spin_element*/
GC_child_CisAisCitAiu_spin_element()
void GC_child_CisAisCitAiu_spin_element (long int j, long int org_sigma2, long int org_sigma4, long int isA_up, long int isB_up, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int * tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{it}^\dagger c_{iu}\) term of grandcanonical spsin system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] org_sigma2 Target for spin 1
[in] org_sigma4 Target for spin 2
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] tmp_V Coupling constatnt
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[out] tmp_off Index of final wavefunction
Definition at line 413 of file mltplySpinCore.cpp.
References X_SpinGC_CisAis(), and X_SpinGC_CisAit().
Referenced by expec_cisajscktalt_SpinGCHalf(), and GC_child_general_int_spin().
   {
   int tmp_sgn;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_SpinGC_CisAit(j, isB_up, org_sigma4, tmp_off);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_SpinGC_CisAis((*tmp_off + 1), isA_up, org_sigma2);
     if (tmp_sgn != 0) {
       dmv = (std::complex<double>)tmp_sgn * tmp_V;
       zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[*tmp_off + 1][0], &one);
     }/*if (tmp_sgn != 0)*/
   }/*if (tmp_sgn != 0)*/
 }/*std::complex<double> GC_child_CisAisCitAiu_spin_element*/
GC_child_CisAitCiuAiu_spin_element()
void GC_child_CisAitCiuAiu_spin_element (long int j, long int org_sigma2, long int org_sigma4, long int isA_up, long int isB_up, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int * tmp_off)
Compute \(c_{is}^\dagger c_{it} c_{iu}^\dagger c_{iu}\) term of grandcanonical spsin system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] org_sigma2 Target for spin 1
[in] org_sigma4 Target for spin 2
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] tmp_V Coupling constatnt
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[out] tmp_off Index of final wavefunction
Definition at line 442 of file mltplySpinCore.cpp.
References X_SpinGC_CisAis(), and X_SpinGC_CisAit().
Referenced by expec_cisajscktalt_SpinGCHalf(), and GC_child_general_int_spin().
   {
   int tmp_sgn;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_SpinGC_CisAis(j, isB_up, org_sigma4);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_SpinGC_CisAit(j, isA_up, org_sigma2, tmp_off);
     if (tmp_sgn != 0) {
       dmv = (std::complex<double>)tmp_sgn * tmp_V;
       zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[*tmp_off + 1][0], &one);
     }/*if (tmp_sgn != 0)*/
   }/*if (tmp_sgn != 0)*/
 }/*std::complex<double> GC_child_CisAitCiuAiu_spin_element*/
GC_child_CisAitCiuAiv_spin_element()
void GC_child_CisAitCiuAiv_spin_element (long int j, long int org_sigma2, long int org_sigma4, long int isA_up, long int isB_up, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int * tmp_off_2)
Compute \(c_{is}^\dagger c_{it} c_{iu}^\dagger c_{iv}\) term of grandcanonical spsin system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] org_sigma2 Target for spin 1
[in] org_sigma4 Target for spin 2
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] tmp_V Coupling constatnt
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[out] tmp_off_2 Index of final wavefunction
Definition at line 471 of file mltplySpinCore.cpp.
References X_SpinGC_CisAit().
Referenced by expec_cisajscktalt_SpinGCHalf(), and GC_child_general_int_spin().
   {
   int tmp_sgn;
   long int tmp_off_1;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_SpinGC_CisAit(j, isB_up, org_sigma4, &tmp_off_1);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_SpinGC_CisAit((tmp_off_1 + 1), isA_up, org_sigma2, tmp_off_2);
     if (tmp_sgn != 0) {
       dmv = (std::complex<double>)tmp_sgn * tmp_V;
       zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[*tmp_off_2 + 1][0], &one);
     }/*if (tmp_sgn != 0)*/
   }/*if (tmp_sgn != 0)*/
 }/*std::complex<double> GC_child_CisAitCiuAiv_spin_element*/
GC_child_exchange_spin_element()
void GC_child_exchange_spin_element (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int * tmp_off)
Multiply Hamiltonian of exchange term of grandcanonical spin system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 299 of file mltplySpinCore.cpp.
References LargeList::isA_spin, BindStruct::Large, and LargeList::tmp_J.
Referenced by GC_child_exchange_spin().
   {
   long int is_up = X->Large.isA_spin;
   std::complex<double> tmp_J = X->Large.tmp_J;
   long int list_1_j, list_1_off;
   int one = 1;
   list_1_j = j - 1;
   long int ibit_tmp;
   ibit_tmp = (list_1_j & is_up);
   if (ibit_tmp == 0 || ibit_tmp == is_up) {
     return;
   }
   else {
     list_1_off = list_1_j ^ is_up;
     *tmp_off = list_1_off;
     zaxpy_(&nstate, &tmp_J, &tmp_v1[j][0], &one, &tmp_v0[list_1_off + 1][0], &one);
   }
 }/*std::complex<double> GC_child_exchange_spin_element*/
GC_child_pairlift_spin_element()
void GC_child_pairlift_spin_element (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int * tmp_off)
Multiply Hamiltonian of pairlift term of grandcanonical spin system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 329 of file mltplySpinCore.cpp.
References LargeList::isA_spin, BindStruct::Large, and LargeList::tmp_J.
Referenced by GC_child_pairlift_spin().
   {
   long int is_up = X->Large.isA_spin;
   std::complex<double> tmp_J = X->Large.tmp_J;
   int one = 1;
   long int list_1_off;
   long int list_1_j = j - 1;
   long int ibit_tmp;
   //ibit_tmp = ((list_1_j & is1_up) / is1_up) ^ ((list_1_j & is2_up) / is2_up);
   ibit_tmp = (list_1_j & is_up);
   if (ibit_tmp == 0 || ibit_tmp == is_up) {
     list_1_off = list_1_j ^ is_up; //Change: ++ -> -- or -- -> ++
     *tmp_off = list_1_off;
     zaxpy_(&nstate, &tmp_J, &tmp_v1[j][0], &one, &tmp_v0[list_1_off + 1][0], &one);
   }
 }/*std::complex<double> GC_child_pairlift_spin_element*/
X_child_exchange_spin_element()
int X_child_exchange_spin_element (long int j, struct BindStruct * X, long int isA_up, long int isB_up, long int sigmaA, long int sigmaB, long int * tmp_off)
Compute index of final wavefunction associated to spin-exchange term.
Returns
1 if spin of site 1 is sigmaA and spin of site 2 is sigmaB. 0 if not.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] X
[in] isA_up Bit mask for spin 1
[in] isB_up Bit mask for spin 2
[in] sigmaA Target of spin 1
[in] sigmaB Target of spin 2
[out] tmp_off Index of final wavefunction
Definition at line 233 of file mltplySpinCore.cpp.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_2_1, and list_2_2.
Referenced by child_general_int_spin(), and expec_cisajscktalt_SpinHalf().
   {
   long int iexchg, off;
   long int irght = X->Large.irght;
   long int ilft = X->Large.ilft;
   long int ihfbit = X->Large.ihfbit;
   long int ibit_tmp_A, ibit_tmp_B;
   ibit_tmp_A = ((list_1[j] & isA_up) / isA_up);
   ibit_tmp_B = ((list_1[j] & isB_up) / isB_up);
   if (ibit_tmp_A == sigmaA && ibit_tmp_B == sigmaB) {
     iexchg = list_1[j] ^ (isA_up + isB_up);
     GetOffComp(list_2_1, list_2_2, iexchg, irght, ilft, ihfbit, &off);
     *tmp_off = off;
     return 1;
   }
   else {
     *tmp_off = 0; // just tentative
     return 0;
   }
 }/*int X_child_exchange_spin_element*/
X_Spin_CisAis()
int X_Spin_CisAis (long int j, long int is1_spin, long int sigma1)
Compute the spin state with bit mask is1_spin.
Returns
1 if the spin state with bit mask is1_spin is sigma1, 0 for the other.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of wavefunction
[in] is1_spin Bit mask
[in] sigma1 Target spin state
Definition at line 163 of file mltplySpinCore.cpp.
References list_1.
Referenced by child_CisAisCisAis_spin_element(), expec_cisajs_SpinHalf(), expec_cisajscktalt_SpinHalf(), GetPairExcitedStateHalfSpin(), SetDiagonalInterAll(), and SetDiagonalTEInterAll().
   {
   int A_ibit_tmp;
   // off = j
   A_ibit_tmp = ((list_1[j] & is1_spin) / is1_spin) ^ (1 - sigma1);
   return A_ibit_tmp;
 }/*int X_Spin_CisAis*/
X_Spin_CisAit()
int X_Spin_CisAit (long int j, struct BindStruct * X, long int is1_spin, long int sigma2, long int * tmp_off)
Compute index of final wavefunction by \(c_{is}^\dagger c_{it}\) term.
Returns
1 if bit-mask is1_spin is sigma2, 0 for the other
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] X
[in] is1_spin Bit mask for computing spin state
[in] sigma2 Spin state at site 2
[out] tmp_off Index of final wavefunction
Definition at line 138 of file mltplySpinCore.cpp.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1_org, list_2_1, list_2_2, and X_SpinGC_CisAit().
Referenced by GetPairExcitedStateHalfSpin().
   {
   long int list_1_j;
   long int off;
   list_1_j = list_1_org[j];
   if (X_SpinGC_CisAit(list_1_j + 1, is1_spin, sigma2, &off) != 0) {
     GetOffComp(list_2_1, list_2_2, off, X->Large.irght, X->Large.ilft, X->Large.ihfbit, tmp_off);
     return 1;
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }/*int X_Spin_CisAit*/
X_SpinGC_CisAis()
int X_SpinGC_CisAis (long int j, long int is1_spin, long int sigma1)
Compute the grandcanonical spin state with bit mask is1_spin.
Returns
1 if the spin state with bit mask is1_spin is sigma1, 0 for the other.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of wavefunction
[in] is1_spin Bit mask
[in] sigma1 Target spin state
Definition at line 179 of file mltplySpinCore.cpp.
Referenced by expec_cisajs_SpinGCHalf(), expec_cisajs_SpinHalf(), expec_cisajscktalt_SpinHalf(), GC_child_CisAisCisAis_spin_element(), GC_child_CisAisCitAiu_spin_element(), GC_child_CisAitCiuAiu_spin_element(), GetPairExcitedStateHalfSpin(), SetDiagonalInterAll(), SetDiagonalTEInterAll(), totalspin_Spin(), totalspin_SpinGC(), X_GC_child_CisAisCjuAju_spin_MPIdouble(), X_GC_child_CisAisCjuAju_spin_MPIsingle(), X_GC_child_CisAisCjuAjv_spin_MPIdouble(), and X_GC_child_CisAitCjuAju_spin_MPIdouble().
   {
   int A_ibit_tmp;
   long int list_1_j;
   // off = j
   list_1_j = j - 1;
   A_ibit_tmp = ((list_1_j & is1_spin) / is1_spin) ^ (1 - sigma1);
   return A_ibit_tmp;
 }/*int X_SpinGC_CisAis*/
X_SpinGC_CisAit()
int X_SpinGC_CisAit (long int j, long int is1_spin, long int sigma2, long int * tmp_off)
Compute index of final wavefunction by \(c_{is}^\dagger c_{it}\) term (grandcanonical).
Returns
1 if bit-mask is1_spin is sigma2, 0 for the other
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of wavefunction
[in] is1_spin Bit mask for computing spin state
[in] sigma2 Spin state at site 2
[out] tmp_off Index of final wavefunction
Definition at line 198 of file mltplySpinCore.cpp.
Referenced by expec_cisajs_SpinGCHalf(), GC_child_CisAisCitAiu_spin_element(), GC_child_CisAitCiuAiu_spin_element(), GC_child_CisAitCiuAiv_spin_element(), mltplyHalfSpinGC(), X_GC_child_CisAitCiuAiv_spin_MPIsingle(), and X_Spin_CisAit().
   {
   long int list_1_j, ibit_tmp_1;
   list_1_j = j - 1;
   ibit_tmp_1 = list_1_j & is1_spin;
   if (ibit_tmp_1 == 0 && sigma2 == 0) {    // down -> up
     *tmp_off = list_1_j + is1_spin;
     return 1;
   }
   else if (ibit_tmp_1 != 0 && sigma2 == 1) { // up -> down
     *tmp_off = list_1_j - is1_spin;
     return 1;
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }/*int X_SpinGC_CisAit*/