HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/mltplyHubbardCore.cpp File Reference
mltplyHubbardCore.cpp File Reference
Functions for Hubbard hamiltonian (Core)
#include <bitcalc.hpp>
#include "xsetmem.hpp"
#include "wrapperMPI.hpp"
#include "mltplyCommon.hpp"
#include "mltplyHubbardCore.hpp"
Functions
int child_general_hopp_GetInfo (struct BindStruct *X, long int isite1, long int isite2, long int sigma1, long int sigma2)
Compute mask for bit operation of hopping term.
int child_general_int_GetInfo (struct BindStruct *X, long int isite1, long int isite2, long int isite3, long int isite4, long int sigma1, long int sigma2, long int sigma3, long int sigma4, std::complex< double > tmp_V)
Compute mask for bit operation of general interaction term.
int child_pairhopp_GetInfo (int iPairHopp, struct BindStruct *X)
Compute mask for bit operation of pairhop term.
int child_exchange_GetInfo (int iExchange, struct BindStruct *X)
Compute mask for bit operation of exchange term.
void GC_CisAis (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int is1_spin, std::complex< double > tmp_trans)
Operation of \(t c_{i\sigma}^\dagger c_{i\sigma}\) (Grandcanonical)
void GC_AisCis (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int is1_spin, std::complex< double > tmp_trans)
Operation of \(t c_{i\sigma} c_{i\sigma}^\dagger\) (Grandcanonical)
int X_CisAis (long int list_1_j, long int is1_spin)
\(c_{is}\\dagger c_{is}\) term in Hubbard (canonical)
void CisAjt (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int is1_spin, long int is2_spin, long int sum_spin, long int diff_spin, std::complex< double > tmp_V)
\(c_{is}^\dagger c_{jt}\) term for canonical Hubbard
void GC_CisAjt (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int is1_spin, long int is2_spin, long int sum_spin, long int diff_spin, std::complex< double > tmp_V, long int *tmp_off)
\(c_{is}^\dagger c_{jt}\) term for grandcanonical Hubbard
int X_CisAjt (long int list_1_j, struct BindStruct *X, long int is1_spin, long int is2_spin, long int sum_spin, long int diff_spin, long int *tmp_off)
Compute index of wavefunction of final state.
int X_GC_CisAjt (long int list_1_j, long int is1_spin, long int is2_spin, long int sum_spin, long int diff_spin, long int *tmp_off)
Compute index of wavefunction of final state.
void child_exchange_element (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int *tmp_off)
Compute exchange term of canonical-Hubbard.
void child_pairhopp_element (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int *tmp_off)
Compute pairhopp term of canonical Hubbard system.
void GC_child_exchange_element (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int *tmp_off)
Compute exchange term of grandcanonical Hubbard system.
void GC_child_pairhopp_element (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int *tmp_off)
Compute pairhopp term of grandcanonical Hubbard system.
void child_CisAisCisAis_element (long int j, long int isite1, long int isite3, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of canonical Hubbard system.
void child_CisAisCjtAku_element (long int j, long int isite1, long int isite3, long int isite4, long int Bsum, long int Bdiff, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int *tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{jt}^\dagger c_{ku}\) term of canonical Hubbard system.
void child_CisAjtCkuAku_element (long int j, long int isite1, long int isite2, long int isite3, long int Asum, long int Adiff, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int *tmp_off)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{ku}\) term of canonical Hubbard system.
void child_CisAjtCkuAlv_element (long int j, long int isite1, long int isite2, long int isite3, long int isite4, long int Asum, long int Adiff, long int Bsum, long int Bdiff, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, struct BindStruct *X, long int *tmp_off_2)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{lv}\) term of canonical Hubbard system.
void GC_child_CisAisCisAis_element (long int j, long int isite1, long int isite3, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of grandcanonical Hubbard system.
void GC_child_CisAisCjtAku_element (long int j, long int isite1, long int isite3, long int isite4, long int Bsum, long int Bdiff, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int *tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{jt}^\dagger c_{ku}\) term of grandcanonical Hubbard system.
void GC_child_CisAjtCkuAku_element (long int j, long int isite1, long int isite2, long int isite3, long int Asum, long int Adiff, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int *tmp_off)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{ku}\) term of grandcanonical Hubbard system.
void GC_child_CisAjtCkuAlv_element (long int j, long int isite1, long int isite2, long int isite3, long int isite4, long int Asum, long int Adiff, long int Bsum, long int Bdiff, std::complex< double > tmp_V, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int *tmp_off_2)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{lv}\) term of grandcanonical Hubbard system.
void GC_Cis (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int is1_spin, std::complex< double > tmp_V, long int *tmp_off)
Compute \(c_{is}^\dagger\) term of grandcanonical Hubbard system.
void GC_Ajt (long int j, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1, long int is1_spin, std::complex< double > tmp_V, long int *tmp_off)
Compute \(c_{jt}\) term of grandcanonical Hubbard system.
int X_Cis (long int j, long int is1_spin, long int *tmp_off, long int *list_1_org, long int *list_2_1_target, long int *list_2_2_target, long int _irght, long int _ilft, long int _ihfbit)
Compute index of final wavefunction associatesd to \(c_{is}^\dagger\) term of canonical Hubbard system.
int X_Ajt (long int j, long int is1_spin, long int *tmp_off, long int *list_1_org, long int *list_2_1_target, long int *list_2_2_target, long int _irght, long int _ilft, long int _ihfbit)
Compute index of final wavefunction associatesd to \(c_{jt}\) term of canonical Hubbard system.
Detailed Description
Functions for Hubbard hamiltonian (Core)
Definition in file mltplyHubbardCore.cpp.
Function Documentation
child_CisAisCisAis_element()
void child_CisAisCisAis_element (long int j, long int isite1, long int isite3, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of canonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite3 Site 3
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
Definition at line 629 of file mltplyHubbardCore.cpp.
References list_1, and X_CisAis().
Referenced by child_general_int(), and expec_cisajscktalt_Hubbard().
   {
   int tmp_sgn;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_CisAis(list_1[j], isite3);
   tmp_sgn *= X_CisAis(list_1[j], isite1);
   dmv = tmp_V * (std::complex<double>)tmp_sgn;
   zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[j][0], &one);
 }/*std::complex<double> child_CisAisCisAis_element*/
child_CisAisCjtAku_element()
void child_CisAisCjtAku_element (long int j, long int isite1, long int isite3, long int isite4, long int Bsum, long int Bdiff, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int * tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{jt}^\dagger c_{ku}\) term of canonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite3 Site 3
[in] isite4 Site 4
[in] Bsum Bit mask for hopping
[in] Bdiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 651 of file mltplyHubbardCore.cpp.
References list_1, X_CisAis(), and X_CisAjt().
Referenced by child_general_int(), and expec_cisajscktalt_Hubbard().
   {
   int tmp_sgn;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_CisAjt(list_1[j], X, isite3, isite4, Bsum, Bdiff, tmp_off);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_CisAis(list_1[*tmp_off], isite1);
     if (tmp_sgn != 0) {
       dmv = tmp_V * (std::complex<double>)tmp_sgn;
       zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[*tmp_off][0], &one);
     }
   }
 }/*std::complex<double> child_CisAisCjtAku_element*/
child_CisAjtCkuAku_element()
void child_CisAjtCkuAku_element (long int j, long int isite1, long int isite2, long int isite3, long int Asum, long int Adiff, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int * tmp_off)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{ku}\) term of canonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite2 Site 2
[in] isite3 Site 3
[in] Asum Bit mask for hopping
[in] Adiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 682 of file mltplyHubbardCore.cpp.
References list_1, X_CisAis(), and X_CisAjt().
Referenced by child_general_int(), and expec_cisajscktalt_Hubbard().
   {
   int tmp_sgn;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_CisAis(list_1[j], isite3);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_CisAjt(list_1[j], X, isite1, isite2, Asum, Adiff, tmp_off);
     if (tmp_sgn != 0) {
       dmv = tmp_V * (std::complex<double>)tmp_sgn;
       zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[*tmp_off][0], &one);
     }
   }
 }/*std::complex<double> child_CisAjtCkuAku_element*/
child_CisAjtCkuAlv_element()
void child_CisAjtCkuAlv_element (long int j, long int isite1, long int isite2, long int isite3, long int isite4, long int Asum, long int Adiff, long int Bsum, long int Bdiff, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int * tmp_off_2)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{lv}\) term of canonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite2 Site 2
[in] isite3 Site 3
[in] isite4 Site 4
[in] Asum Bit mask for hopping
[in] Adiff Bit mask for Fermion sign
[in] Bsum Bit mask for hopping
[in] Bdiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off_2 Index of final wavefunction
Definition at line 713 of file mltplyHubbardCore.cpp.
References list_1, X_CisAjt(), and X_GC_CisAjt().
Referenced by child_general_int(), and expec_cisajscktalt_Hubbard().
   {
   int tmp_sgn;
   long int tmp_off_1;
   int one = 1;
   std::complex<double> dmv;
   tmp_sgn = X_GC_CisAjt(list_1[j], isite3, isite4, Bsum, Bdiff, &tmp_off_1);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_CisAjt(tmp_off_1, X, isite1, isite2, Asum, Adiff, tmp_off_2);
     if (tmp_sgn != 0) {
       dmv = tmp_V * (std::complex<double>)tmp_sgn;
       zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[*tmp_off_2][0], &one);
     }
   }
 }/*std::complex<double> child_CisAjtCkuAlv_element*/
child_exchange_element()
void child_exchange_element (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int * tmp_off)
Compute exchange term of canonical-Hubbard.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] tmp_v0 \(v_0 = H v_1\)
[in] tmp_v1 Vector to be producted
[in,out] X
tmp_off [off] Index of wavefunction of final state
Definition at line 442 of file mltplyHubbardCore.cpp.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, list_1, list_2_1, list_2_2, and LargeList::tmp_J.
Referenced by child_exchange().
   {
   long int off;
   long int ibit1_up, ibit2_up, ibit1_down, ibit2_down;
   std::complex<double> dmv;
   long int iexchg;
   long int is1_up = X->Large.is1_up;
   long int is2_up = X->Large.is2_up;
   long int is1_down = X->Large.is1_down;
   long int is2_down = X->Large.is2_down;
   long int irght = X->Large.irght;
   long int ilft = X->Large.ilft;
   long int ihfbit = X->Large.ihfbit;
   std::complex<double> tmp_J = X->Large.tmp_J;
   int one = 1;
   ibit1_up = list_1[j] & is1_up;
   ibit2_up = list_1[j] & is2_up;
   ibit1_down = list_1[j] & is1_down;
   ibit2_down = list_1[j] & is2_down;
   if (ibit1_up == 0 && ibit1_down != 0 && ibit2_up != 0 && ibit2_down == 0) {
     iexchg = list_1[j] - (is1_down + is2_up);
     iexchg += (is1_up + is2_down);
     if(GetOffComp(list_2_1, list_2_2, iexchg, irght, ilft, ihfbit, &off)!=TRUE){
       return;
     }
     *tmp_off = off;
     dmv = tmp_J;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[off][0], &one);
   }
   else if (ibit1_up != 0 && ibit1_down == 0 && ibit2_up == 0 && ibit2_down != 0) {
     iexchg = list_1[j] - (is1_up + is2_down);
     iexchg += (is1_down + is2_up);
     if(GetOffComp(list_2_1, list_2_2, iexchg, irght, ilft, ihfbit, &off)!=TRUE){
       return;
     }
     *tmp_off = off;
     dmv = tmp_J;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[off][0], &one);
   }
 }/*std::complex<double> child_exchange_element*/
child_exchange_GetInfo()
int child_exchange_GetInfo (int iExchange, struct BindStruct * X)
Compute mask for bit operation of exchange term.
Returns
Error-code, always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Copy coupling constant (LargeList::tmp_J)
Compute mask for checking occupations of \((i_1,\uparrow)\) (LargeList::is1_up), \((i_1,\downarrow)\) (LargeList::is1_down) \((i_2,\uparrow)\) (LargeList::is2_up), \((i_2,\downarrow)\) (LargeList::is2_down)
Parameters
[in] iExchange Index of exchange interaction
[in,out] X
Definition at line 196 of file mltplyHubbardCore.cpp.
References BindStruct::Def, DefineList::ExchangeCoupling, LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, DefineList::ParaExchangeCoupling, LargeList::tmp_J, and DefineList::Tpow.
Referenced by mltplyHubbard(), and mltplyHubbardGC().
   {
   int isite1 = X->Def.ExchangeCoupling[iExchange][0] + 1;
   int isite2 = X->Def.ExchangeCoupling[iExchange][1] + 1;
   X->Large.tmp_J = -X->Def.ParaExchangeCoupling[iExchange];
   X->Large.is1_up = X->Def.Tpow[2 * isite1 - 2];
   X->Large.is1_down = X->Def.Tpow[2 * isite1 - 1];
   X->Large.is2_up = X->Def.Tpow[2 * isite2 - 2];
   X->Large.is2_down = X->Def.Tpow[2 * isite2 - 1];
   return 0;
 }/*int child_exchange_GetInfo*/
child_general_hopp_GetInfo()
int child_general_hopp_GetInfo (struct BindStruct * X, long int isite1, long int isite2, long int sigma1, long int sigma2)
Compute mask for bit operation of hopping term.
Returns
Error-code, always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Compute mask for checking occupations of \((i_1,\sigma_1)\) (LargeList::is1_spin) and \((i_2,\sigma_2)\) (LargeList::is2_spin)
Compute mask for Fermion sign (LargeList::A_spin)
Compute mask for hopping (LargeList::isA_spin)
Parameters
[in,out] X
[in] isite1 Site index
[in] isite2 Site index
[in] sigma1 Spin index
[in] sigma2 Spin index
Definition at line 34 of file mltplyHubbardCore.cpp.
References LargeList::A_spin, BindStruct::Def, LargeList::is1_spin, LargeList::is2_spin, LargeList::isA_spin, BindStruct::Large, and DefineList::Tpow.
Referenced by expec_cisajs_Hubbard(), expec_cisajs_HubbardGC(), GetPairExcitedStateHubbard(), GetPairExcitedStateHubbardGC(), mltplyHalfSpinGC(), mltplyHubbard(), and mltplyHubbardGC().
   {
   X->Large.is1_spin = X->Def.Tpow[2 * isite1 - 2 + sigma1];
   X->Large.is2_spin = X->Def.Tpow[2 * isite2 - 2 + sigma2];
   if (isite1 > isite2) {
     X->Large.A_spin = (X->Def.Tpow[2 * isite1 - 2 + sigma1] - X->Def.Tpow[2 * isite2 - 1 + sigma2]);
   }
   else if (isite1 < isite2) {
     X->Large.A_spin = (X->Def.Tpow[2 * isite2 - 2 + sigma2] - X->Def.Tpow[2 * isite1 - 1 + sigma1]);
   }
   else {
     if (sigma1 > sigma2) {
       X->Large.A_spin = (X->Def.Tpow[2 * isite1 - 2 + sigma1] - X->Def.Tpow[2 * isite2 - 1 + sigma2]);
     }
     else {
       X->Large.A_spin = (X->Def.Tpow[2 * isite2 - 2 + sigma2] - X->Def.Tpow[2 * isite1 - 1 + sigma1]);
     }
   }
   X->Large.isA_spin = X->Large.is1_spin + X->Large.is2_spin;
   return 0;
 }/*int child_general_hopp_GetInfo*/
child_general_int_GetInfo()
int child_general_int_GetInfo (struct BindStruct * X, long int isite1, long int isite2, long int isite3, long int isite4, long int sigma1, long int sigma2, long int sigma3, long int sigma4, std::complex< double > tmp_V)
Compute mask for bit operation of general interaction term.
Returns
Error-code, always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Compute mask for checking occupations of \((i_1,\sigma_1)\) (LargeList::is1_spin) and \((i_2,\sigma_2)\) (LargeList::is2_spin)
Compute mask for Fermion sign (LargeList::A_spin)
Compute mask for checking occupations of \((i_3,\sigma_3)\) (LargeList::is3_spin) and \((i_4,\sigma_4)\) (LargeList::is4_spin)
Compute mask for Fermion sign (LargeList::B_spin)
Compute mask for hopping (LargeList::isA_spin, LargeList::isB_spin)
Copy coupling constant (LargeList::tmp_V)
Parameters
[in,out] X
[in] isite1 Site index
[in] isite2 Site index
[in] isite3 Site index
[in] isite4 Site index
[in] sigma1 Spin index
[in] sigma2 Spin index
[in] sigma3 Spin index
[in] sigma4 Spin index
[in] tmp_V Coupling constant
Definition at line 76 of file mltplyHubbardCore.cpp.
References LargeList::A_spin, LargeList::B_spin, BindStruct::Def, LargeList::is1_spin, LargeList::is2_spin, LargeList::is3_spin, LargeList::is4_spin, LargeList::isA_spin, LargeList::isB_spin, LargeList::isite1, LargeList::isite2, LargeList::isite3, LargeList::isite4, BindStruct::Large, LargeList::tmp_V, and DefineList::Tpow.
Referenced by expec_cisajscktalt_Hubbard(), expec_cisajscktalt_HubbardGC(), mltplyHubbard(), and mltplyHubbardGC().
   {
   long int is1_spin, is2_spin, is3_spin, is4_spin;
   long int A_spin, B_spin;
   long int isA_spin, isB_spin;
   is1_spin = X->Def.Tpow[2 * isite1 - 2 + sigma1];
   is2_spin = X->Def.Tpow[2 * isite2 - 2 + sigma2];
   if (isite1 > isite2) {
     A_spin = (X->Def.Tpow[2 * isite1 - 2 + sigma1] - X->Def.Tpow[2 * isite2 - 1 + sigma2]);
   }
   else if (isite2 > isite1) {
     A_spin = (X->Def.Tpow[2 * isite2 - 2 + sigma2] - X->Def.Tpow[2 * isite1 - 1 + sigma1]);
   }
   else {//isite1=isite2
     if (sigma1 > sigma2) {
       A_spin = (X->Def.Tpow[2 * isite1 - 2 + sigma1] - X->Def.Tpow[2 * isite2 - 1 + sigma2]);
     }
     else {
       A_spin = (X->Def.Tpow[2 * isite2 - 2 + sigma2] - X->Def.Tpow[2 * isite1 - 1 + sigma1]);
     }
   }
   is3_spin = X->Def.Tpow[2 * isite3 - 2 + sigma3];
   is4_spin = X->Def.Tpow[2 * isite4 - 2 + sigma4];
   if (isite3 > isite4) {
     B_spin = (X->Def.Tpow[2 * isite3 - 2 + sigma3] - X->Def.Tpow[2 * isite4 - 1 + sigma4]);
   }
   else if (isite3 < isite4) {
     B_spin = (X->Def.Tpow[2 * isite4 - 2 + sigma4] - X->Def.Tpow[2 * isite3 - 1 + sigma3]);
   }
   else {//isite3=isite4
     if (sigma3 > sigma4) {
       B_spin = (X->Def.Tpow[2 * isite3 - 2 + sigma3] - X->Def.Tpow[2 * isite4 - 1 + sigma4]);
     }
     else {
       B_spin = (X->Def.Tpow[2 * isite4 - 2 + sigma4] - X->Def.Tpow[2 * isite3 - 1 + sigma3]);
     }
   }
   isA_spin = is1_spin + is2_spin;
   isB_spin = is3_spin + is4_spin;
   X->Large.is1_spin = is1_spin;
   X->Large.is2_spin = is2_spin;
   X->Large.is3_spin = is3_spin;
   X->Large.is4_spin = is4_spin;
   X->Large.isA_spin = isA_spin;
   X->Large.isB_spin = isB_spin;
   X->Large.A_spin = A_spin;
   X->Large.B_spin = B_spin;
   X->Large.tmp_V = tmp_V;
   X->Large.isite1 = isite1;
   X->Large.isite2 = isite2;
   X->Large.isite3 = isite3;
   X->Large.isite4 = isite4;
   return 0;
 }/*int child_general_int_GetInfo*/
child_pairhopp_element()
void child_pairhopp_element (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int * tmp_off)
Compute pairhopp term of canonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 494 of file mltplyHubbardCore.cpp.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, list_1, list_2_1, list_2_2, and LargeList::tmp_J.
Referenced by child_pairhopp().
   {
   long int off;
   long int ibit1_up, ibit2_up, ibit1_down, ibit2_down;
   std::complex<double> dmv;
   long int iexchg;
   long int is1_up = X->Large.is1_up;
   long int is2_up = X->Large.is2_up;
   long int is1_down = X->Large.is1_down;
   long int is2_down = X->Large.is2_down;
   long int irght = X->Large.irght;
   long int ilft = X->Large.ilft;
   long int ihfbit = X->Large.ihfbit;
   std::complex<double> tmp_J = X->Large.tmp_J;
   int one = 1;
   ibit1_up = list_1[j] & is1_up;
   ibit2_up = list_1[j] & is2_up;
   ibit1_down = list_1[j] & is1_down;
   ibit2_down = list_1[j] & is2_down;
   if (ibit1_up == 0 && ibit1_down == 0 && ibit2_up != 0 && ibit2_down != 0) {
     iexchg = list_1[j] - (is2_up + is2_down);
     iexchg += (is1_up + is1_down);
     if(GetOffComp(list_2_1, list_2_2, iexchg, irght, ilft, ihfbit, &off)!=TRUE){
       return;
     }
     *tmp_off = off;
     dmv = tmp_J;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[off][0], &one);
   }
 }/*std::complex<double> child_pairhopp_element*/
child_pairhopp_GetInfo()
int child_pairhopp_GetInfo (int iPairHopp, struct BindStruct * X)
Compute mask for bit operation of pairhop term.
Returns
Error-code, always return 0
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Copy coupling constant (LargeList::tmp_J)
Compute mask for checking occupations of \((i_1,\uparrow)\) (LargeList::is1_up), \((i_1,\downarrow)\) (LargeList::is1_down) \((i_2,\uparrow)\) (LargeList::is2_up), \((i_2,\downarrow)\) (LargeList::is2_down)
Parameters
[in] iPairHopp Index of pairhopp interaction
[in,out] X
Definition at line 168 of file mltplyHubbardCore.cpp.
References BindStruct::Def, LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, DefineList::PairHopping, DefineList::ParaPairHopping, LargeList::tmp_J, and DefineList::Tpow.
Referenced by mltplyHubbard(), and mltplyHubbardGC().
   {
   int isite1 = X->Def.PairHopping[iPairHopp][0] + 1;
   int isite2 = X->Def.PairHopping[iPairHopp][1] + 1;
   X->Large.tmp_J = X->Def.ParaPairHopping[iPairHopp];
   X->Large.is1_up = X->Def.Tpow[2 * isite1 - 2];
   X->Large.is1_down = X->Def.Tpow[2 * isite1 - 1];
   X->Large.is2_up = X->Def.Tpow[2 * isite2 - 2];
   X->Large.is2_down = X->Def.Tpow[2 * isite2 - 1];
   return 0;
 }/*int child_pairhopp_GetInfo*/
CisAjt()
void CisAjt (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int is1_spin, long int is2_spin, long int sum_spin, long int diff_spin, std::complex< double > tmp_V)
\(c_{is}^\dagger c_{jt}\) term for canonical Hubbard
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of wavefunction
[in,out] tmp_v0 \(v_0 = H v_1\)
[in] tmp_v1 Vector to be producted
[in,out] X
[in] is1_spin Mask for occupation of (is)
[in] is2_spin Mask for occupation of (jt)
[in] sum_spin Mask for hopping
[in] diff_spin Mask for Fermion sign
[in] tmp_V Hopping integral
Definition at line 291 of file mltplyHubbardCore.cpp.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_2_1, list_2_2, and SgnBit().
Referenced by child_general_hopp(), X_child_CisAjtCkuAku_Hubbard_MPI(), and X_child_CisAjtCkuAlv_Hubbard_MPI().
   {
   long int ibit_tmp_1, ibit_tmp_2;
   long int bit, iexchg, off;
   int sgn;
   std::complex<double> dmv;
   int one = 1;
   ibit_tmp_1 = (list_1[j] & is1_spin);
   ibit_tmp_2 = (list_1[j] & is2_spin);
   if (ibit_tmp_1 == 0 && ibit_tmp_2 != 0) {
     bit = list_1[j] & diff_spin;
     SgnBit(bit, &sgn); // Fermion sign
     iexchg = list_1[j] ^ sum_spin;
     if(GetOffComp(list_2_1, list_2_2, iexchg, X->Large.irght, X->Large.ilft, X->Large.ihfbit, &off)==FALSE){
       return;
     }
     dmv = (std::complex<double>)sgn * tmp_V;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[off][0], &one);
   }
   else {
     return;
   }
 }
GC_AisCis()
void GC_AisCis (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int is1_spin, std::complex< double > tmp_trans)
Operation of \(t c_{i\sigma} c_{i\sigma}^\dagger\) (Grandcanonical)
Author
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of element of wavefunction
[in,out] tmp_v0 Result vector
[in] tmp_v1 Input producted vector
[in] is1_spin Mask for occupation of \((i \sigma)\)
[in] tmp_trans Transfer integral
Definition at line 253 of file mltplyHubbardCore.cpp.
Referenced by GetPairExcitedStateHubbardGC().
   {
   long int A_ibit_tmp;
   long int list_1_j;
   std::complex<double> dmv;
   int one = 1;
   list_1_j = j - 1;
   A_ibit_tmp = (list_1_j & is1_spin) / is1_spin;
   dmv = tmp_trans * (std::complex<double>)(1 - A_ibit_tmp);
   zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[j][0], &one);
 }/*std::complex<double> GC_AisCis*/
GC_Ajt()
void GC_Ajt (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int is1_spin, std::complex< double > tmp_V, long int * tmp_off)
Compute \(c_{jt}\) term of grandcanonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Youhei Yamaji (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in] is1_spin Bit mask
[in] tmp_V Coupling constant
[in] tmp_off Index of final wavefunction
Definition at line 919 of file mltplyHubbardCore.cpp.
References myrank, and SgnBit().
Referenced by GetSingleExcitedStateHubbardGC().
   {
   long int list_1_j, list_1_off;
   long int ibit_tmp_1;
   long int bit;
   int sgn, ipsgn;
   std::complex<double> dmv;
   int one = 1;
   list_1_j = j - 1;
   ibit_tmp_1 = (list_1_j & is1_spin);
   // is1_spin >= 1
   *tmp_off = 0;
   if (ibit_tmp_1 == is1_spin) {
     // able to create an electron at the is1_spin state
     bit = list_1_j - (list_1_j & (2 * is1_spin - 1));
     SgnBit(bit, &sgn); // Fermion sign
     ipsgn = 1;
 #ifdef __MPI
     SgnBit(myrank, &ipsgn); // Fermion sign
 #endif
     list_1_off = list_1_j ^ is1_spin;
     *tmp_off = list_1_off;
     dmv = (std::complex<double>)(ipsgn * sgn) * tmp_V;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[list_1_off + 1][0], &one);
   }
   else {
     return;
   }
 }/*std::complex<double> GC_Ajt*/
GC_child_CisAisCisAis_element()
void GC_child_CisAisCisAis_element (long int j, long int isite1, long int isite3, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Compute \(c_{is}^\dagger c_{is} c_{is}^\dagger c_{is}\) term of grandcanonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite3 Site 3
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
Definition at line 751 of file mltplyHubbardCore.cpp.
References X_CisAis().
Referenced by expec_cisajscktalt_HubbardGC(), and GC_child_general_int().
   {
   int tmp_sgn;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_CisAis(j - 1, isite3);
   tmp_sgn *= X_CisAis(j - 1, isite1);
   if (tmp_sgn != 0) {
     dmv = tmp_V * (std::complex<double>)tmp_sgn;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[j][0], &one);
   }
 }/*std::complex<double> GC_child_CisAisCisAis_element*/
GC_child_CisAisCjtAku_element()
void GC_child_CisAisCjtAku_element (long int j, long int isite1, long int isite3, long int isite4, long int Bsum, long int Bdiff, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int * tmp_off)
Compute \(c_{is}^\dagger c_{is} c_{jt}^\dagger c_{ku}\) term of grandcanonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite3 Site 3
[in] isite4 Site 4
[in] Bsum Bit mask for hopping
[in] Bdiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[out] tmp_off Index of final wavefunction
Definition at line 775 of file mltplyHubbardCore.cpp.
References X_CisAis(), and X_GC_CisAjt().
Referenced by expec_cisajscktalt_HubbardGC(), and GC_child_general_int().
   {
   int tmp_sgn;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_GC_CisAjt((j - 1), isite3, isite4, Bsum, Bdiff, tmp_off);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_CisAis(*tmp_off, isite1);
     if (tmp_sgn != 0) {
       dmv = tmp_V * (std::complex<double>)tmp_sgn;
       zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[*tmp_off + 1][0], &one);
     }
   }
 }/*std::complex<double> GC_child_CisAisCjtAku_element*/
GC_child_CisAjtCkuAku_element()
void GC_child_CisAjtCkuAku_element (long int j, long int isite1, long int isite2, long int isite3, long int Asum, long int Adiff, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int * tmp_off)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{ku}\) term of grandcanonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite2 Site 2
[in] isite3 Site 3
[in] Asum Bit mask for hopping
[in] Adiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[out] tmp_off Index of final wavefunction
Definition at line 805 of file mltplyHubbardCore.cpp.
References X_CisAis(), and X_GC_CisAjt().
Referenced by expec_cisajscktalt_HubbardGC(), and GC_child_general_int().
   {
   int tmp_sgn;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_CisAis(j - 1, isite3);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_GC_CisAjt(j - 1, isite1, isite2, Asum, Adiff, tmp_off);
     if (tmp_sgn != 0) {
       dmv = tmp_V * (std::complex<double>)tmp_sgn;
       zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[*tmp_off + 1][0], &one);
     }/*if (tmp_sgn != 0)*/
   }/*if (tmp_sgn != 0)*/
 }/*std::complex<double> GC_child_CisAjtCkuAku_element*/
GC_child_CisAjtCkuAlv_element()
void GC_child_CisAjtCkuAlv_element (long int j, long int isite1, long int isite2, long int isite3, long int isite4, long int Asum, long int Adiff, long int Bsum, long int Bdiff, std::complex< double > tmp_V, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int * tmp_off_2)
Compute \(c_{is}^\dagger c_{jt} c_{ku}^\dagger c_{lv}\) term of grandcanonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] isite1 Site 1
[in] isite2 Site 2
[in] isite3 Site 3
[in] isite4 Site 4
[in] Asum Bit mask for hopping
[in] Adiff Bit mask for Fermion sign
[in] Bsum Bit mask for hopping
[in] Bdiff Bit mask for Fermion sign
[in] tmp_V Coupling constant
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[out] tmp_off_2 Index of final wavefunction
Definition at line 835 of file mltplyHubbardCore.cpp.
References X_GC_CisAjt().
Referenced by expec_cisajscktalt_HubbardGC(), and GC_child_general_int().
   {
   int tmp_sgn;
   long int tmp_off_1;
   std::complex<double> dmv;
   int one = 1;
   tmp_sgn = X_GC_CisAjt(j - 1, isite3, isite4, Bsum, Bdiff, &tmp_off_1);
   if (tmp_sgn != 0) {
     tmp_sgn *= X_GC_CisAjt(tmp_off_1, isite1, isite2, Asum, Adiff, tmp_off_2);
     if (tmp_sgn != 0) {
       dmv = tmp_V * (std::complex<double>)tmp_sgn;
       zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[*tmp_off_2 + 1][0], &one);
     }
   }
 }/*std::complex<double> GC_child_CisAjtCkuAlv_element*/
GC_child_exchange_element()
void GC_child_exchange_element (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int * tmp_off)
Compute exchange term of grandcanonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 537 of file mltplyHubbardCore.cpp.
References LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, and LargeList::tmp_J.
Referenced by GC_child_exchange().
   {
   long int ibit1_up, ibit2_up, ibit1_down, ibit2_down;
   std::complex<double> dmv;
   long int iexchg;
   long int is1_up = X->Large.is1_up;
   long int is2_up = X->Large.is2_up;
   long int is1_down = X->Large.is1_down;
   long int is2_down = X->Large.is2_down;
   long int list_1_j, list_1_off;
   std::complex<double> tmp_J = X->Large.tmp_J;
   int one = 1;
   list_1_j = j - 1;
   ibit1_up = list_1_j & is1_up;
   ibit2_up = list_1_j & is2_up;
   ibit1_down = list_1_j & is1_down;
   ibit2_down = list_1_j & is2_down;
   if (ibit1_up == 0 && ibit1_down != 0 && ibit2_up != 0 && ibit2_down == 0) {
     iexchg = list_1_j - (is1_down + is2_up);
     iexchg += (is1_up + is2_down);
     list_1_off = iexchg;
     *tmp_off = list_1_off;
     dmv = tmp_J;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[list_1_off + 1][0], &one);
   }
   else if (ibit1_up != 0 && ibit1_down == 0 && ibit2_up == 0 && ibit2_down != 0) {
     iexchg = list_1_j - (is1_up + is2_down);
     iexchg += (is1_down + is2_up);
     list_1_off = iexchg;
     *tmp_off = list_1_off;
     dmv = tmp_J;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[list_1_off + 1][0], &one);
   }
 }/*std::complex<double> GC_child_exchange_element*/
GC_child_pairhopp_element()
void GC_child_pairhopp_element (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, struct BindStruct * X, long int * tmp_off)
Compute pairhopp term of grandcanonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in,out] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in,out] X
[out] tmp_off Index of final wavefunction
Definition at line 586 of file mltplyHubbardCore.cpp.
References LargeList::is1_down, LargeList::is1_up, LargeList::is2_down, LargeList::is2_up, BindStruct::Large, and LargeList::tmp_J.
Referenced by GC_child_pairhopp().
   {
   long int ibit1_up, ibit2_up, ibit1_down, ibit2_down;
   std::complex<double> dmv;
   long int iexchg;
   long int is1_up = X->Large.is1_up;
   long int is2_up = X->Large.is2_up;
   long int is1_down = X->Large.is1_down;
   long int is2_down = X->Large.is2_down;
   long int list_1_j, list_1_off;
   std::complex<double> tmp_J = X->Large.tmp_J;
   int one = 1;
   list_1_j = j - 1;
   ibit1_up = list_1_j & is1_up;
   ibit2_up = list_1_j & is2_up;
   ibit1_down = list_1_j & is1_down;
   ibit2_down = list_1_j & is2_down;
   if (ibit1_up == 0 && ibit1_down == 0 && ibit2_up != 0 && ibit2_down != 0) {
     iexchg = list_1_j - (is2_up + is2_down);
     iexchg += (is1_up + is1_down);
     list_1_off = iexchg;
     *tmp_off = list_1_off;
     dmv = tmp_J;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[list_1_off + 1][0], &one);
   }
 }
GC_Cis()
void GC_Cis (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int is1_spin, std::complex< double > tmp_V, long int * tmp_off)
Compute \(c_{is}^\dagger\) term of grandcanonical Hubbard system.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Youhei Yamaji (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] tmp_v0 Resulting wavefunction
[in] tmp_v1 Wavefunction to be multiplied
[in] is1_spin Bit mask
[in] tmp_V Coupling constant
[in] tmp_off Index of final wavefunction
Definition at line 872 of file mltplyHubbardCore.cpp.
References myrank, and SgnBit().
Referenced by GetSingleExcitedStateHubbardGC().
   {
   long int list_1_j, list_1_off;
   long int ibit_tmp_1;
   long int bit;
   int sgn, ipsgn;
   std::complex<double> dmv;
   int one = 1;
   list_1_j = j - 1;
   ibit_tmp_1 = (list_1_j & is1_spin);
   // is1_spin >= 1
   // is1_spin = Tpow[2*isite + ispin]
   *tmp_off = 0;
   if (ibit_tmp_1 == 0) {
     // able to create an electron at the is1_spin state
     bit = list_1_j - (list_1_j & (2 * is1_spin - 1));
     SgnBit(bit, &sgn); // Fermion sign
     ipsgn = 1;
 #ifdef __MPI
     SgnBit(myrank, &ipsgn); // Fermion sign
 #endif
     list_1_off = list_1_j | is1_spin; // OR
     *tmp_off = list_1_off;
     dmv = (std::complex<double>)(ipsgn * sgn) * tmp_V;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[list_1_off + 1][0], &one);
   }
   else {
     return;
   }
 }/*std::complex<double> GC_Cis*/
GC_CisAis()
void GC_CisAis (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int is1_spin, std::complex< double > tmp_trans)
Operation of \(t c_{i\sigma}^\dagger c_{i\sigma}\) (Grandcanonical)
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of element of wavefunction
[in,out] tmp_v0 Result vector
[in] tmp_v1 Input producted vector
[in] is1_spin Mask for occupation of \((i \sigma)\)
[in] tmp_trans Transfer integral
Definition at line 231 of file mltplyHubbardCore.cpp.
Referenced by GC_child_general_hopp().
   {
   long int A_ibit_tmp;
   long int list_1_j;
   std::complex<double> dmv;
   int one = 1;
   list_1_j = j - 1;
   A_ibit_tmp = (list_1_j & is1_spin) / is1_spin;
   dmv = tmp_trans * (std::complex<double>)A_ibit_tmp;
   zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[j][0], &one);
 }/*std::complex<double> GC_CisAis*/
GC_CisAjt()
void GC_CisAjt (long int j, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1, long int is1_spin, long int is2_spin, long int sum_spin, long int diff_spin, std::complex< double > tmp_V, long int * tmp_off)
\(c_{is}^\dagger c_{jt}\) term for grandcanonical Hubbard
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] j Index of wavefunction
[in] tmp_v0 \(v_0 = H v_1\)
[in] tmp_v1 Vector to be producted
[in] is1_spin Mask for occupation of (is)
[in] is2_spin Mask for occupation of (jt)
[in] sum_spin Mask for hopping
[in] diff_spin Mask for Fermion sign
[in] tmp_V Hopping
[in] tmp_off Index of wavefunction of final state
Definition at line 330 of file mltplyHubbardCore.cpp.
References SgnBit().
Referenced by GC_child_general_hopp(), X_GC_child_CisAjtCkuAku_Hubbard_MPI(), and X_GC_child_CisAjtCkuAlv_Hubbard_MPI().
   {
   long int list_1_j, list_1_off;
   long int ibit_tmp_1, ibit_tmp_2;
   long int bit;
   int sgn;
   std::complex<double> dmv;
   list_1_j = j - 1;
   ibit_tmp_1 = (list_1_j & is1_spin);
   ibit_tmp_2 = (list_1_j & is2_spin);
   *tmp_off = 0;
   int one = 1;
   if (ibit_tmp_1 == 0 && ibit_tmp_2 != 0) {
     bit = list_1_j & diff_spin;
     SgnBit(bit, &sgn); // Fermion sign
     list_1_off = list_1_j ^ sum_spin;
     *tmp_off = list_1_off;
     dmv = (std::complex<double>)sgn * tmp_V;
     zaxpy_(&nstate, &dmv, &tmp_v1[j][0], &one, &tmp_v0[list_1_off + 1][0], &one);
   }
   else {
     return;
   }
 }/*std::complex<double> GC_CisAjt*/
X_Ajt()
int X_Ajt (long int j, long int is1_spin, long int * tmp_off, long int * list_1_org, long int * list_2_1_target, long int * list_2_2_target, long int _irght, long int _ilft, long int _ihfbit)
Compute index of final wavefunction associatesd to \(c_{jt}\) term of canonical Hubbard system.
Returns
1 if electron (jt) exist, 0 if not.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Youhei Yamaji (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] is1_spin Bit mask
[out] tmp_off Index of final wavefunction
[in] list_1_org Similar to list_1
[in] list_2_1_target Similar to list_2_1
[in] list_2_2_target Similar to list_2_2
[in] _irght Similar to LargeList::irght
[in] _ilft Similar to LargeList::ilft
[in] _ihfbit Similar to LargeList::ihfbit
Definition at line 1020 of file mltplyHubbardCore.cpp.
References GetOffComp(), myrank, and SgnBit().
Referenced by GetSingleExcitedStateHubbard().
   {
   long int list_1_j, list_1_off;
   long int ibit_tmp_1;
   long int bit;
   int sgn, ipsgn;
   list_1_j = list_1_org[j];
   ibit_tmp_1 = (list_1_j & is1_spin);
 // is1_spin >= 1
 // is1_spin = Tpow[2*isite + ispin]
   *tmp_off = 0;
   if (ibit_tmp_1 != 0) {
     // able to delete an electron at the is1_spin state
     bit = list_1_j - (list_1_j & (2 * is1_spin - 1));
     SgnBit(bit, &sgn); // Fermion sign
     ipsgn = 1;
 #ifdef __MPI
     SgnBit(myrank, &ipsgn); // Fermion sign
 #endif
     list_1_off = list_1_j ^ is1_spin;
     if(GetOffComp(list_2_1_target, list_2_2_target, list_1_off, _irght, _ilft, _ihfbit, tmp_off)!=TRUE){
       *tmp_off=0;
       return 0;
     }
     sgn *= ipsgn;
     return(sgn);
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }/*std::complex<double> X_Ajt*/
X_Cis()
int X_Cis (long int j, long int is1_spin, long int * tmp_off, long int * list_1_org, long int * list_2_1_target, long int * list_2_2_target, long int _irght, long int _ilft, long int _ihfbit)
Compute index of final wavefunction associatesd to \(c_{is}^\dagger\) term of canonical Hubbard system.
Returns
1 if electron (is) absent, 0 if not.
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Youhei Yamaji (The University of Tokyo)
Parameters
[in] j Index of initial wavefunction
[in] is1_spin Bit mask
[out] tmp_off Index of final wavefunction
[in] list_1_org Similar to list_1
[in] list_2_1_target Similar to list_2_1
[in] list_2_2_target Similar to list_2_2
[in] _irght Similar to LargeList::irght
[in] _ilft Similar to LargeList::ilft
[in] _ihfbit Similar to LargeList::ihfbit
Definition at line 966 of file mltplyHubbardCore.cpp.
References GetOffComp(), myrank, and SgnBit().
Referenced by GetSingleExcitedStateHubbard().
   {
   long int list_1_j, list_1_off;
   long int ibit_tmp_1;
   long int bit;
   int sgn, ipsgn;
   list_1_j = list_1_org[j];
   ibit_tmp_1 = (list_1_j & is1_spin);
   // is1_spin >= 1
   // is1_spin = Tpow[2*isite + ispin]
   *tmp_off = 0;
   if (ibit_tmp_1 == 0) {
     // able to create an electron at the is1_spin state
     bit = list_1_j - (list_1_j & (2 * is1_spin - 1));
     SgnBit(bit, &sgn); // Fermion sign
     ipsgn = 1;
 #ifdef __MPI
     SgnBit(myrank, &ipsgn); // Fermion sign
 #endif
     list_1_off = list_1_j | is1_spin; // OR
     if(GetOffComp(list_2_1_target, list_2_2_target, list_1_off, _irght, _ilft, _ihfbit, tmp_off)!=TRUE){
       *tmp_off=0;
       return 0;
     }
     sgn *= ipsgn;
     return (sgn);
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }/*int X_Cis*/
X_CisAis()
int X_CisAis (long int list_1_j, long int is1_spin)
\(c_{is}\\dagger c_{is}\) term in Hubbard (canonical)
Returns
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Definition at line 276 of file mltplyHubbardCore.cpp.
Referenced by child_CisAisCisAis_element(), child_CisAisCjtAku_element(), child_CisAjtCkuAku_element(), GC_child_CisAisCisAis_element(), GC_child_CisAisCjtAku_element(), GC_child_CisAjtCkuAku_element(), and X_child_CisAis_Hubbard_MPI().
   {
   int A_ibit_tmp;
   // off = j
   A_ibit_tmp = (list_1_j & is1_spin) / is1_spin;
   return A_ibit_tmp;
 }
X_CisAjt()
int X_CisAjt (long int list_1_j, struct BindStruct * X, long int is1_spin, long int is2_spin, long int sum_spin, long int diff_spin, long int * tmp_off)
Compute index of wavefunction of final state.
Returns
Fermion sign
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] list_1_j Similer to list_1 ?
[in] X
[in] is1_spin Mask for occupation of (is)
[in] is2_spin Mask for occupation of (jt)
[in] sum_spin Mask for hopping
[in] diff_spin Mask for Fermion sign
[in] tmp_off Index of wavefunction of final state
Definition at line 371 of file mltplyHubbardCore.cpp.
References GetOffComp(), LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_2_1, list_2_2, and X_GC_CisAjt().
Referenced by child_CisAisCjtAku_element(), child_CisAjtCkuAku_element(), child_CisAjtCkuAlv_element(), and GetPairExcitedStateHubbard().
   {
   long int off;
   int sgn = 1;
   sgn = X_GC_CisAjt(list_1_j, is1_spin, is2_spin, sum_spin, diff_spin, tmp_off);
   if (sgn != 0) {
     if(GetOffComp(list_2_1, list_2_2, *tmp_off, X->Large.irght, X->Large.ilft, X->Large.ihfbit, &off)!=TRUE){
       *tmp_off = 0;
       return 0;
     }
     *tmp_off = off;
     return sgn;
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }/*int X_CisAjt*/
X_GC_CisAjt()
int X_GC_CisAjt (long int list_1_j, long int is1_spin, long int is2_spin, long int sum_spin, long int diff_spin, long int * tmp_off)
Compute index of wavefunction of final state.
Returns
Fermion sign
Author
Takahiro Misawa (The University of Tokyo)
Kazuyoshi Yoshimi (The University of Tokyo)
Parameters
[in] list_1_j list_1 ?
[in] is1_spin Mask for occupation of (is)
[in] is2_spin Mask for occupation of (jt)
[in] sum_spin Mask for hopping
[in] diff_spin Mask for Fermion sign
[out] tmp_off Index of wavefunction of final state
Definition at line 403 of file mltplyHubbardCore.cpp.
References SgnBit().
Referenced by child_CisAjtCkuAlv_element(), GC_child_CisAisCjtAku_element(), GC_child_CisAjtCkuAku_element(), GC_child_CisAjtCkuAlv_element(), GetSgnInterAll(), X_child_CisAjtCkuAlv_Hubbard_MPI(), X_CisAjt(), and X_GC_child_CisAjtCkuAlv_Hubbard_MPI().
   {
   long int ibit_tmp_1, ibit_tmp_2;
   long int bit, off;
   int sgn = 1;
   ibit_tmp_1 = (list_1_j & is1_spin);
   ibit_tmp_2 = (list_1_j & is2_spin);
   if (ibit_tmp_1 == 0 && ibit_tmp_2 != 0) {
     bit = list_1_j & diff_spin;
     SgnBit(bit, &sgn); // Fermion sign
     off = list_1_j ^ sum_spin;
     *tmp_off = off;
     return sgn; // pm 1
   }
   else {
     *tmp_off = 0;
     return 0;
   }
 }