HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/mltplyMPISpin.cpp File Reference
mltplyMPISpin.cpp File Reference
Functions for spin Hamiltonian + MPI.
#include "Common.hpp"
#include "mltplyCommon.hpp"
#include "bitcalc.hpp"
#include "wrapperMPI.hpp"
#include "mltplyMPISpin.hpp"
#include "mltplyMPISpinCore.hpp"
Functions
void child_general_int_spin_MPIdouble (long int i_int, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
void X_child_general_int_spin_MPIdouble (int org_isite1, int org_ispin1, int org_ispin2, int org_isite3, int org_ispin3, int org_ispin4, std::complex< double > tmp_J, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
void X_child_general_int_spin_TotalS_MPIdouble (int org_isite1, int org_isite3, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
void child_general_int_spin_MPIsingle (long int i_int, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
Exchange term in Spin model When only site2 is in the inter process region.
void X_child_general_int_spin_MPIsingle (int org_isite1, int org_ispin1, int org_ispin2, int org_isite3, int org_ispin3, int org_ispin4, std::complex< double > tmp_J, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
void GC_child_general_int_spin_MPIdouble (long int i_int, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
void GC_child_general_int_spin_MPIsingle (long int i_int, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
void GC_child_general_int_GeneralSpin_MPIdouble (long int i_int, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
void GC_child_general_int_GeneralSpin_MPIsingle (long int i_int, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
void child_general_int_GeneralSpin_MPIdouble (long int i_int, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
void child_general_int_GeneralSpin_MPIsingle (long int i_int, struct BindStruct *X, int nstate, std::complex< double > **tmp_v0, std::complex< double > **tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Detailed Description
Functions for spin Hamiltonian + MPI.
Definition in file mltplyMPISpin.cpp.
Function Documentation
child_general_int_GeneralSpin_MPIdouble()
void child_general_int_GeneralSpin_MPIdouble (long int i_int, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 337 of file mltplyMPISpin.cpp.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, DefineList::ParaInterAll_OffDiagonal, and X_child_CisAitCjuAjv_GeneralSpin_MPIdouble().
Referenced by mltplyGeneralSpin().
  {
     X_child_CisAitCjuAjv_GeneralSpin_MPIdouble(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
       X->Def.InterAll_OffDiagonal[i_int][5], X->Def.InterAll_OffDiagonal[i_int][7],
       X->Def.ParaInterAll_OffDiagonal[i_int], X, nstate, tmp_v0, tmp_v1);
 }/*void GC_child_general_int_spin_MPIdouble*/
child_general_int_GeneralSpin_MPIsingle()
void child_general_int_GeneralSpin_MPIsingle (long int i_int, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 355 of file mltplyMPISpin.cpp.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, DefineList::ParaInterAll_OffDiagonal, and X_child_CisAitCjuAjv_GeneralSpin_MPIsingle().
Referenced by mltplyGeneralSpin().
  {
   X_child_CisAitCjuAjv_GeneralSpin_MPIsingle(
     X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
     X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
     X->Def.InterAll_OffDiagonal[i_int][5], X->Def.InterAll_OffDiagonal[i_int][7],
     X->Def.ParaInterAll_OffDiagonal[i_int], X, nstate, tmp_v0, tmp_v1);
 }/*void GC_child_general_int_spin_MPIsingle*/
child_general_int_spin_MPIdouble()
void child_general_int_spin_MPIdouble (long int i_int, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 32 of file mltplyMPISpin.cpp.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, DefineList::ParaInterAll_OffDiagonal, and X_child_general_int_spin_MPIdouble().
Referenced by mltplyHalfSpin().
  {
   X_child_general_int_spin_MPIdouble(
     (int)X->Def.InterAll_OffDiagonal[i_int][0], (int)X->Def.InterAll_OffDiagonal[i_int][1],
     (int)X->Def.InterAll_OffDiagonal[i_int][3], (int)X->Def.InterAll_OffDiagonal[i_int][4],
     (int)X->Def.InterAll_OffDiagonal[i_int][5], (int)X->Def.InterAll_OffDiagonal[i_int][7],
     X->Def.ParaInterAll_OffDiagonal[i_int], X, nstate, tmp_v0, tmp_v1);
 }/*void child_general_int_spin_MPIdouble*/
child_general_int_spin_MPIsingle()
void child_general_int_spin_MPIsingle (long int i_int, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Exchange term in Spin model When only site2 is in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 141 of file mltplyMPISpin.cpp.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, DefineList::ParaInterAll_OffDiagonal, and X_child_general_int_spin_MPIsingle().
Referenced by mltplyHalfSpin().
  {
   X_child_general_int_spin_MPIsingle(
     (int)X->Def.InterAll_OffDiagonal[i_int][0], (int)X->Def.InterAll_OffDiagonal[i_int][1],
     (int)X->Def.InterAll_OffDiagonal[i_int][3], (int)X->Def.InterAll_OffDiagonal[i_int][4],
     (int)X->Def.InterAll_OffDiagonal[i_int][5], (int)X->Def.InterAll_OffDiagonal[i_int][7],
     X->Def.ParaInterAll_OffDiagonal[i_int], X, nstate, tmp_v0, tmp_v1);
 }/*void child_general_int_spin_MPIsingle*/
GC_child_general_int_GeneralSpin_MPIdouble()
void GC_child_general_int_GeneralSpin_MPIdouble (long int i_int, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 268 of file mltplyMPISpin.cpp.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, DefineList::ParaInterAll_OffDiagonal, X_GC_child_CisAisCjuAjv_GeneralSpin_MPIdouble(), X_GC_child_CisAitCjuAju_GeneralSpin_MPIdouble(), and X_GC_child_CisAitCjuAjv_GeneralSpin_MPIdouble().
Referenced by mltplyGeneralSpinGC().
  {
   if (X->Def.InterAll_OffDiagonal[i_int][1] == X->Def.InterAll_OffDiagonal[i_int][3] &&
       X->Def.InterAll_OffDiagonal[i_int][5] != X->Def.InterAll_OffDiagonal[i_int][7]) {
     X_GC_child_CisAisCjuAjv_GeneralSpin_MPIdouble(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][4], X->Def.InterAll_OffDiagonal[i_int][5],
       X->Def.InterAll_OffDiagonal[i_int][7], X->Def.ParaInterAll_OffDiagonal[i_int], X, nstate, tmp_v0, tmp_v1);
   }
   else if (X->Def.InterAll_OffDiagonal[i_int][1] != X->Def.InterAll_OffDiagonal[i_int][3] &&
            X->Def.InterAll_OffDiagonal[i_int][5] == X->Def.InterAll_OffDiagonal[i_int][7]) {
     X_GC_child_CisAitCjuAju_GeneralSpin_MPIdouble(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
       X->Def.InterAll_OffDiagonal[i_int][5], X->Def.ParaInterAll_OffDiagonal[i_int], X, nstate, tmp_v0, tmp_v1);
   }
   else {
     X_GC_child_CisAitCjuAjv_GeneralSpin_MPIdouble(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
       X->Def.InterAll_OffDiagonal[i_int][5], X->Def.InterAll_OffDiagonal[i_int][7],
       X->Def.ParaInterAll_OffDiagonal[i_int], X, nstate, tmp_v0, tmp_v1);
   }
 }/*void GC_child_general_int_spin_MPIdouble*/
GC_child_general_int_GeneralSpin_MPIsingle()
void GC_child_general_int_GeneralSpin_MPIsingle (long int i_int, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 302 of file mltplyMPISpin.cpp.
References BindStruct::Def, DefineList::InterAll_OffDiagonal, DefineList::ParaInterAll_OffDiagonal, X_GC_child_CisAisCjuAjv_GeneralSpin_MPIsingle(), X_GC_child_CisAitCjuAju_GeneralSpin_MPIsingle(), and X_GC_child_CisAitCjuAjv_GeneralSpin_MPIsingle().
Referenced by mltplyGeneralSpinGC().
  {
   if (X->Def.InterAll_OffDiagonal[i_int][1] == X->Def.InterAll_OffDiagonal[i_int][3] &&
       X->Def.InterAll_OffDiagonal[i_int][5] != X->Def.InterAll_OffDiagonal[i_int][7]) {
     X_GC_child_CisAisCjuAjv_GeneralSpin_MPIsingle(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][4], X->Def.InterAll_OffDiagonal[i_int][5],
       X->Def.InterAll_OffDiagonal[i_int][7], X->Def.ParaInterAll_OffDiagonal[i_int], X, nstate, tmp_v0, tmp_v1);
   }
   else if (X->Def.InterAll_OffDiagonal[i_int][1] != X->Def.InterAll_OffDiagonal[i_int][3] &&
            X->Def.InterAll_OffDiagonal[i_int][5] == X->Def.InterAll_OffDiagonal[i_int][7]) {
     X_GC_child_CisAitCjuAju_GeneralSpin_MPIsingle(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
       X->Def.InterAll_OffDiagonal[i_int][5], X->Def.ParaInterAll_OffDiagonal[i_int], X, nstate, tmp_v0, tmp_v1);
     }
   else {
     X_GC_child_CisAitCjuAjv_GeneralSpin_MPIsingle(
       X->Def.InterAll_OffDiagonal[i_int][0], X->Def.InterAll_OffDiagonal[i_int][1],
       X->Def.InterAll_OffDiagonal[i_int][3], X->Def.InterAll_OffDiagonal[i_int][4],
       X->Def.InterAll_OffDiagonal[i_int][5], X->Def.InterAll_OffDiagonal[i_int][7],
       X->Def.ParaInterAll_OffDiagonal[i_int], X, nstate, tmp_v0, tmp_v1);
   }
 }/*void GC_child_general_int_spin_MPIsingle*/
GC_child_general_int_spin_MPIdouble()
void GC_child_general_int_spin_MPIdouble (long int i_int, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 222 of file mltplyMPISpin.cpp.
References BindStruct::Def, GC_child_CisAisCjuAjv_spin_MPIdouble(), GC_child_CisAitCiuAiv_spin_MPIdouble(), GC_child_CisAitCjuAju_spin_MPIdouble(), and DefineList::InterAll_OffDiagonal.
Referenced by mltplyHalfSpinGC().
  {
   if (X->Def.InterAll_OffDiagonal[i_int][1] == X->Def.InterAll_OffDiagonal[i_int][3] &&
       X->Def.InterAll_OffDiagonal[i_int][5] != X->Def.InterAll_OffDiagonal[i_int][7]) {
     GC_child_CisAisCjuAjv_spin_MPIdouble(i_int, X, nstate, tmp_v0, tmp_v1);
   }
   else if (X->Def.InterAll_OffDiagonal[i_int][1] != X->Def.InterAll_OffDiagonal[i_int][3] &&
            X->Def.InterAll_OffDiagonal[i_int][5] == X->Def.InterAll_OffDiagonal[i_int][7]) {
     GC_child_CisAitCjuAju_spin_MPIdouble(i_int, X, nstate, tmp_v0, tmp_v1);
   }
   else {
     GC_child_CisAitCiuAiv_spin_MPIdouble(i_int, X, nstate, tmp_v0, tmp_v1);
   }
 }/*void GC_child_general_int_spin_MPIdouble*/
GC_child_general_int_spin_MPIsingle()
void GC_child_general_int_spin_MPIsingle (long int i_int, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
General interaction term in the Spin model + GC When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] i_int Interaction ID
[in,out] X
[out] tmp_v0 Result v0 = H v1
[in] tmp_v1 v0 = H v1
Definition at line 245 of file mltplyMPISpin.cpp.
References BindStruct::Def, GC_child_CisAisCjuAjv_spin_MPIsingle(), GC_child_CisAitCiuAiv_spin_MPIsingle(), GC_child_CisAitCjuAju_spin_MPIsingle(), and DefineList::InterAll_OffDiagonal.
Referenced by mltplyHalfSpinGC().
  {
   if (X->Def.InterAll_OffDiagonal[i_int][1] == X->Def.InterAll_OffDiagonal[i_int][3] &&
       X->Def.InterAll_OffDiagonal[i_int][5] != X->Def.InterAll_OffDiagonal[i_int][7]) {
     GC_child_CisAisCjuAjv_spin_MPIsingle(i_int, X, nstate, tmp_v0, tmp_v1);
   }
   else if (X->Def.InterAll_OffDiagonal[i_int][1] != X->Def.InterAll_OffDiagonal[i_int][3] &&
            X->Def.InterAll_OffDiagonal[i_int][5] == X->Def.InterAll_OffDiagonal[i_int][7]) {
     GC_child_CisAitCjuAju_spin_MPIsingle(i_int, X, nstate, tmp_v0, tmp_v1);
   }
   else {
     GC_child_CisAitCiuAiv_spin_MPIsingle(i_int, X, nstate, tmp_v0, tmp_v1);
   }
 }/*void GC_child_general_int_spin_MPIsingle*/
X_child_general_int_spin_MPIdouble()
void X_child_general_int_spin_MPIdouble (int org_isite1, int org_ispin1, int org_ispin2, int org_isite3, int org_ispin3, int org_ispin4, std::complex< double > tmp_J, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] org_isite1 Site 1
[in] org_ispin1 Spin 1
[in] org_ispin2 Spin 2
[in] org_isite3 Site 3
[in] org_ispin3 Spin 3
[in] org_ispin4 Spin 4
[in] tmp_J Copupling constatnt
[in,out] X
[in,out] tmp_v0 \({\bf v}_0=H {\bf v}_1\)
[in] tmp_v1 Vector to be producted
Definition at line 49 of file mltplyMPISpin.cpp.
References BindStruct::Check, BindStruct::Def, GetOffComp(), CheckList::idim_max, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_1buf, list_2_1, list_2_2, LargeList::mode, myrank, SendRecv_cv(), SendRecv_i(), SendRecv_iv(), DefineList::Tpow, and v1buf.
Referenced by child_general_int_spin_MPIdouble(), expec_cisajscktalt_SpinHalf(), and mltplyHalfSpin().
   {
   int mask1, mask2, state1, state2, origin;
   long int idim_max_buf, j, ioff;
   std::complex<double> Jint;
   int one = 1;
   mask1 = (int)X->Def.Tpow[org_isite1];
   mask2 = (int)X->Def.Tpow[org_isite3];
   origin = myrank ^ (mask1 + mask2);
   state1 = (origin & mask1) / mask1;
   state2 = (origin & mask2) / mask2;
   if (state1 == org_ispin2 && state2 == org_ispin4) {
     Jint = tmp_J;
   }
   else if (state1 == org_ispin1 && state2 == org_ispin3) {
     Jint = conj(tmp_J);
     if (X->Large.mode == M_CORR || X->Large.mode == M_CALCSPEC) {
       Jint = 0;
     }
   }
   else return;
   idim_max_buf = SendRecv_i(origin, X->Check.idim_max);
   SendRecv_iv(origin, X->Check.idim_max + 1, idim_max_buf + 1, list_1, list_1buf);
   SendRecv_cv(origin, X->Check.idim_max*nstate, idim_max_buf*nstate, &tmp_v1[1][0], &v1buf[1][0]);
 #pragma omp parallel for default(none)  private(j, ioff) \
   firstprivate(idim_max_buf,Jint,X) shared(list_2_1,list_2_2,list_1buf,v1buf,tmp_v1,tmp_v0,nstate,one)
   for (j = 1; j <= idim_max_buf; j++) {
     GetOffComp(list_2_1, list_2_2, list_1buf[j],
         X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
     zaxpy_(&nstate, &Jint, &v1buf[j][0], &one, &tmp_v0[ioff][0], &one);
   }/*for (j = 1; j <= idim_max_buf; j++)*/
 }/*std::complex<double> X_child_general_int_spin_MPIdouble*/
X_child_general_int_spin_MPIsingle()
void X_child_general_int_spin_MPIsingle (int org_isite1, int org_ispin1, int org_ispin2, int org_isite3, int org_ispin3, int org_ispin4, std::complex< double > tmp_J, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Parameters
[in] org_isite1 Site 1
[in] org_ispin1 Spin 1
[in] org_ispin2 Spin 2
[in] org_isite3 Site 3
[in] org_ispin3 Spin 3
[in] org_ispin4 Spin 4
[in] tmp_J Copupling constatnt
[in,out] X
[in,out] tmp_v0 \({\bf v}_0=H {\bf v}_1\)
[in] tmp_v1 Vector to be producted
Definition at line 158 of file mltplyMPISpin.cpp.
References BindStruct::Check, BindStruct::Def, GetOffComp(), CheckList::idim_max, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_1buf, list_2_1, list_2_2, LargeList::mode, myrank, SendRecv_cv(), SendRecv_i(), SendRecv_iv(), DefineList::Tpow, and v1buf.
Referenced by child_general_int_spin_MPIsingle(), expec_cisajscktalt_SpinHalf(), and mltplyHalfSpin().
   {
   int mask2, state2, origin;
   long int mask1, idim_max_buf, j, ioff, state1, jreal, state1check;
   std::complex<double> Jint;
   int one = 1;
   /*
   Prepare index in the inter PE
   */
   mask2 = (int)X->Def.Tpow[org_isite3];
   origin = myrank ^ mask2;
   state2 = (origin & mask2) / mask2;
   if (state2 == org_ispin4) {
     state1check = (long int) org_ispin2;
     Jint = tmp_J;
   }
   else if (state2 == org_ispin3) {
     state1check = (long int) org_ispin1;
     Jint = conj(tmp_J);
     if (X->Large.mode == M_CORR || X->Large.mode == M_CALCSPEC) {
       Jint = 0;
     }
   }
   else return;
   idim_max_buf = SendRecv_i(origin, X->Check.idim_max);
   SendRecv_iv(origin, X->Check.idim_max + 1, idim_max_buf + 1, list_1, list_1buf);
   SendRecv_cv(origin, X->Check.idim_max*nstate, idim_max_buf*nstate, &tmp_v1[1][0], &v1buf[1][0]);
   /*
   Index in the intra PE
   */
   mask1 = X->Def.Tpow[org_isite1];
   //printf("debug1 %ld\n", idim_max_buf);
 #pragma omp parallel for default(none)  private(j, ioff, jreal, state1) \
 firstprivate(idim_max_buf, Jint, X, mask1, state1check, org_isite1) \
 shared(list_2_1, list_2_2, list_1buf, v1buf, tmp_v1, tmp_v0,nstate,one)
   for (j = 1; j <= idim_max_buf; j++) {
     jreal = list_1buf[j];
     state1 = (jreal & mask1) / mask1;
     if (state1 == state1check) {
       GetOffComp(list_2_1, list_2_2, jreal ^ mask1,
         X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
       zaxpy_(&nstate, &Jint, &v1buf[j][0], &one, &tmp_v0[ioff][0], &one);
     }
   }
 }/*std::complex<double> X_child_general_int_spin_MPIsingle*/
X_child_general_int_spin_TotalS_MPIdouble()
void X_child_general_int_spin_TotalS_MPIdouble (int org_isite1, int org_isite3, struct BindStruct * X, int nstate, std::complex< double > ** tmp_v0, std::complex< double > ** tmp_v1)
Exchange term in Spin model When both site1 and site2 are in the inter process region.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] org_isite1 site 1
[in] org_isite3 site 3
[in,out] X
[in,out] tmp_v0 \({\bf v}_0=H {\bf v}_1\)
[in] tmp_v1 Vector to be producted
Definition at line 101 of file mltplyMPISpin.cpp.
References BindStruct::Check, BindStruct::Def, GetOffComp(), CheckList::idim_max, LargeList::ihfbit, LargeList::ilft, LargeList::irght, BindStruct::Large, list_1, list_1buf, list_2_1, list_2_2, myrank, SendRecv_cv(), SendRecv_i(), SendRecv_iv(), DefineList::Tpow, and v1buf.
  {
   int mask1, mask2, num1_up, num2_up, origin, one = 1;
   long int idim_max_buf, j, ioff, ibit_tmp;
   std::complex<double> dmv;
   mask1 = (int)X->Def.Tpow[org_isite1];
   mask2 = (int)X->Def.Tpow[org_isite3];
   if (mask1 == mask2) origin = myrank ^ mask1;
   else origin = myrank ^ (mask1 + mask2);
   num1_up = (origin & mask1) / mask1;
   num2_up = (origin & mask2) / mask2;
   ibit_tmp = (num1_up) ^ (num2_up);
   if (ibit_tmp == 0) return;
   idim_max_buf = SendRecv_i(origin, X->Check.idim_max);
   SendRecv_iv(origin, X->Check.idim_max + 1, idim_max_buf + 1, list_1, list_1buf);
   SendRecv_cv(origin, X->Check.idim_max*nstate, idim_max_buf*nstate, &tmp_v1[1][0], &v1buf[1][0]);
 #pragma omp parallel for default(none)  private(j, dmv, ioff) \
     firstprivate(idim_max_buf, X) \
   shared(list_2_1, list_2_2, list_1buf, v1buf, tmp_v1, tmp_v0,nstate,one)
   for (j = 1; j <= idim_max_buf; j++) {
     GetOffComp(list_2_1, list_2_2, list_1buf[j],
       X->Large.irght, X->Large.ilft, X->Large.ihfbit, &ioff);
     zaxpy_(&nstate, &dmv, &v1buf[j][0], &one, &tmp_v0[ioff][0], &one);
   }/*for (j = 1; j <= idim_max_buf; j++)*/
   return;
 }/*std::complex<double> X_child_general_int_spin_MPIdouble*/