HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/output.cpp File Reference
output.cpp File Reference
#include "output.hpp"
#include "FileIO.hpp"
#include "wrapperMPI.hpp"
Functions
int output (struct BindStruct *X)
output function for FullDiag mode
int outputHam (struct BindStruct *X)
output Hamiltonian only used for FullDiag mode
Function Documentation
output()
int output (struct BindStruct * X)
output function for FullDiag mode
Parameters
[in] X Struct to get information about file header names, dimension of hirbert space, calc type, physical quantities.
Return values
0 normally finished.
-1 abnormally finished.
Definition at line 27 of file output.cpp.
References DefineList::CDataFileHead, BindStruct::Check, childfopenMPI(), BindStruct::Def, PhysList::doublon, PhysList::energy, DefineList::iCalcModel, DefineList::iCalcType, CheckList::idim_max, DefineList::Ndown, PhysList::num_down, PhysList::num_up, DefineList::Nup, BindStruct::Phys, PhysList::s2, stdoutMPI, and PhysList::Sz.
Referenced by CalcByFullDiag().
{
   FILE *fp;
   char sdt[D_FileNameMax];
   long int i, i_max;
   i_max = X->Check.idim_max;
   if (X->Def.iCalcType == FullDiag) {
     switch (X->Def.iCalcModel) {
       case Spin:
       case Hubbard:
       case Kondo:
         sprintf(sdt, "%s_phys_Nup%d_Ndown%d.dat", X->Def.CDataFileHead, X->Def.Nup, X->Def.Ndown);
         break;
       case SpinGC:
       case HubbardGC:
       case KondoGC:
         sprintf(sdt, "%s_phys.dat", X->Def.CDataFileHead);
         break;
       default:
         break;
     }
     if (childfopenMPI(sdt, "w", &fp) != 0) {
       return -1;
     }
     fprintf(fp, "  <H>         <N>        <Sz>       <S2>       <D> \n");
     for (i = 0; i < i_max; i++) {
       fprintf(fp, " %10lf %10lf %10lf %10lf %10lf\n", X->Phys.energy[i], X->Phys.num_up[i]+X->Phys.num_down[i], X->Phys.Sz[i],
               X->Phys.s2[i], X->Phys.doublon[i]);
     }
     fclose(fp);
   }
   else{
     fprintf(stdoutMPI, "Error: output function is used only for FullDiag mode.");
     return -1;
   }
   return 0;
 }
outputHam()
int outputHam (struct BindStruct * X)
output Hamiltonian only used for FullDiag mode
Note
global: [in] Ham
Parameters
[in] X Struct to get information about file header names, dimension of hirbert space.
Return values
0 normally finished.
-1 abnormally finished.
Definition at line 73 of file output.cpp.
References DefineList::CDataFileHead, BindStruct::Check, childfopenMPI(), BindStruct::Def, CheckList::idim_max, and v0.
Referenced by CalcByFullDiag().
{
   long int i=0;
   long int j=0;
   long int imax = X->Check.idim_max;
   long int ihermite=0;
   char cHeader[256];
   FILE *fp;
   char sdt[D_FileNameMax];
 #pragma omp parallel for default(none) reduction(+:ihermite) firstprivate(imax) private(i, j) shared(v0)
   for (i=1; i<=imax; i++){
     for (j=1; j<=i; j++){
       if(abs(v0[i][j])>1.0e-13){
         ihermite += 1;
       }
     }
   }
   strcpy(cHeader, "%%%%MatrixMarket matrix coordinate complex hermitian\n");
   sprintf(sdt,"%s_Ham.dat", X->Def.CDataFileHead);
   if(childfopenMPI(sdt,"w",&fp)!=0){
     return -1;
   }
   fprintf(fp, "%s", cHeader);
   fprintf(fp, "%ld %ld %ld \n", imax, imax, ihermite);
   for (i=1; i<=imax; i++){
     for (j=1; j<=i; j++){
       if(abs(v0[i][j])>1.0e-13){
         fprintf(fp, "%ld %ld %lf %lf\n",i,j,real(v0[i][j]),imag(v0[i][j]));
       }
     }
   }
   fclose(fp);
   return 0;
 }