HPhi++: /mnt/c/Users/kawamuura/program/hphi/hphi/src/wrapperMPI.cpp File Reference
wrapperMPI.cpp File Reference
MPI wrapper for init, finalize, bcast, etc.
#include <mpi.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "wrapperMPI.hpp"
#include <cmath>
#include <complex>
#include "splash.hpp"
#include "global.hpp"
#include "common/setmemory.hpp"
Functions
void InitializeMPI (int argc, char *argv[])
MPI initialization wrapper Process ID (myrank), Number of processes (nproc), Number of threads (nthreads), and pointer to the standard output (stdoutMPI) are specified here.
void FinalizeMPI ()
MPI Finitialization wrapper.
void exitMPI (int errorcode)
MPI Abortation wrapper.
FILE * fopenMPI (const char *FileName, const char *mode)
MPI file I/O (open) wrapper. Only the root node (myrank = 0) should be open/read/write (small) parameter files.
char * fgetsMPI (char *InputString, int maxcount, FILE *fp)
MPI file I/O (get a line, fgets) wrapper. Only the root node (myrank = 0) reads and broadcast string.
void BarrierMPI ()
MPI barrier wrapper.
long int MaxMPI_li (long int idim)
MPI wrapper function to obtain maximum unsigned long integer across processes.
double MaxMPI_d (double dvalue)
MPI wrapper function to obtain maximum Double across processes.
std::complex< double > SumMPI_dc (std::complex< double > norm)
MPI wrapper function to obtain sum of Double complex across processes.
double SumMPI_d (double norm)
MPI wrapper function to obtain sum of Double across processes.
void SumMPI_dv (int nnorm, double *norm)
MPI wrapper function to obtain sum of Double array across processes.
void SumMPI_cv (int nnorm, std::complex< double > *norm)
MPI wrapper function to obtain sum of Double array across processes.
long int SumMPI_li (long int idim)
MPI wrapper function to obtain sum of unsigned long integer across processes.
int SumMPI_i (int idim)
MPI wrapper function to obtain sum of integer across processes.
long int BcastMPI_li (int root, long int idim)
MPI wrapper function to broadcast long integer across processes.
double NormMPI_dc (long int idim, std::complex< double > *_v1)
Compute norm of process-distributed vector \(|{\bf v}_1|^2\).
void NormMPI_dv (long int ndim, int nstate, std::complex< double > **_v1, double *dnorm)
Compute norm of process-distributed vector \(|{\bf v}_1|^2\).
std::complex< double > VecProdMPI (long int ndim, std::complex< double > *v1, std::complex< double > *v2)
Compute conjugate scaler product of process-distributed vector \({\bf v}_1^* \cdot {\bf v}_2\).
void MultiVecProdMPI (long int ndim, int nstate, std::complex< double > **v1, std::complex< double > **v2, std::complex< double > *prod)
Compute conjugate scaler product of process-distributed vector \({\bf v}_1^* \cdot {\bf v}_2\).
void SendRecv_cv (int origin, long int nMsgS, long int nMsgR, std::complex< double > *vecs, std::complex< double > *vecr)
Wrapper of MPI_Sendrecv for std::complex<double> number. When we pass a message longer than 2^31-1 (max of int: 2147483647), we need to divide it.
void SendRecv_iv (int origin, long int nMsgS, long int nMsgR, long int *vecs, long int *vecr)
Wrapper of MPI_Sendrecv for long integer number. When we pass a message longer than 2^31-1 (max of int: 2147483647), we need to divide it.
long int SendRecv_i (int origin, long int isend)
Wrapper of MPI_Sendrecv for long integer number.
Detailed Description
MPI wrapper for init, finalize, bcast, etc.
Definition in file wrapperMPI.cpp.
Function Documentation
BarrierMPI()
void BarrierMPI ()
MPI barrier wrapper.
Author
Mitsuaki Kawamura (The University of Tokyo)
Definition at line 160 of file wrapperMPI.cpp.
                  {
 #ifdef __MPI
   MPI_Barrier(MPI_COMM_WORLD);
 #endif
 }/*void BarrierMPI()*/
BcastMPI_li()
long int BcastMPI_li (int root, long int idim)
MPI wrapper function to broadcast long integer across processes.
Returns
Broadcasted value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] root The source process of the broadcast
[in] idim Value to be broadcasted
Definition at line 305 of file wrapperMPI.cpp.
Referenced by Initialize_wave().
   {
   long int idim0;
   idim0 = idim;
 #ifdef __MPI
     MPI_Bcast(&idim0, 1, MPI_LONG, root, MPI_COMM_WORLD);
 #endif
   return(idim0);
 }/*long int BcastMPI_li*/
exitMPI()
void exitMPI (int errorcode)
MPI Abortation wrapper.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] errorcode Error-code to be returned as that of this program
Definition at line 86 of file wrapperMPI.cpp.
Referenced by CalcByLOBPCG(), CalcByTEM(), CalcByTPQ(), CalcSpectrum(), CalcSpectrumByBiCG(), CheckMPI(), CheckMPI_Summary(), dsfmt_chk_init_by_array(), dsfmt_chk_init_gen_rand(), Initialize_wave(), InitializeMPI(), main(), MakeExcitedList(), MaxMPI_d(), MaxMPI_li(), Output_restart(), phys(), Read_sz(), ReadDefFileIdxPara(), SeedSwitch(), SendRecv_cv(), SendRecv_i(), SendRecv_iv(), SumMPI_cv(), SumMPI_d(), SumMPI_dc(), SumMPI_dv(), SumMPI_i(), SumMPI_li(), sz(), and X_GC_child_CisAjt_Hubbard_MPI().
 {
   fflush(stdout);
 #ifdef __MPI
   fprintf(stdout,"\n\n #######  [HPhi] You DO NOT have to WORRY about the following MPI-ERROR MESSAGE.  #######\n\n");
   int ierr;
   ierr = MPI_Abort(MPI_COMM_WORLD, errorcode);
   ierr = MPI_Finalize();
   if (ierr != 0) fprintf(stderr, "\n  MPI_Finalize() = %d\n\n", ierr);
 #endif
   exit(errorcode);
 }/*void exitMPI*/
fgetsMPI()
char* fgetsMPI (char * InputString, int maxcount, FILE * fp)
MPI file I/O (get a line, fgets) wrapper. Only the root node (myrank = 0) reads and broadcast string.
Returns
The same as that of fgets
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[out] InputString read line.
[in] maxcount Length of string
[in] fp file pointer
Definition at line 122 of file wrapperMPI.cpp.
References myrank.
Referenced by CalcSpectrumByBiCG(), GetFileName(), inputHam(), Read_sz(), ReadcalcmodFile(), ReadDefFileIdxPara(), ReadDefFileNInt(), and SetOmega().
  {
   int inull;
   char *ctmp;
   ctmp = InputString;
   inull = 0;
   if (myrank == 0) {
     ctmp = fgets(InputString, maxcount, fp);
     if (ctmp == NULL){
       inull = 1;
     }
     while(*InputString == '\n' || strncmp(InputString, "#", 1)==0){
       ctmp = fgets(InputString, maxcount, fp);
       if (ctmp == NULL){
         inull=1;
         break;
       }
     }
   }
 #ifdef __MPI
   MPI_Bcast(InputString, maxcount, MPI_CHAR, 0, MPI_COMM_WORLD);
   MPI_Bcast(&inull, 1, MPI_INT, 0, MPI_COMM_WORLD);
 #endif
   if (myrank != 0 && inull == 1) {
     ctmp = NULL;
   }
   return ctmp;
 }/*char* fgetsMPI*/
FinalizeMPI()
void FinalizeMPI ()
MPI Finitialization wrapper.
Author
Mitsuaki Kawamura (The University of Tokyo)
Definition at line 74 of file wrapperMPI.cpp.
References myrank, and stdoutMPI.
Referenced by main(), and MakeExcitedList().
                   {
 #ifdef __MPI
   int ierr;
   ierr = MPI_Finalize();
   if (ierr != 0) fprintf(stderr, "\n  MPI_Finalize() = %d\n\n", ierr);
 #endif
   if (myrank != 0) fclose(stdoutMPI);
 }
fopenMPI()
FILE* fopenMPI (const char * FileName, const char * mode)
MPI file I/O (open) wrapper. Only the root node (myrank = 0) should be open/read/write (small) parameter files.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] FileName Input/output file
[in] mode "w", "r", etc.
Definition at line 105 of file wrapperMPI.cpp.
References myrank.
Referenced by childfopenMPI(), GetFileName(), ReadcalcmodFile(), ReadDefFileIdxPara(), and ReadDefFileNInt().
  {
   FILE* fp;
   if (myrank == 0) fp = fopen(FileName, mode);
   else fp = fopen("/dev/null", "w");
   return fp;
 }/*FILE* fopenMPI*/
InitializeMPI()
void InitializeMPI (int argc, char * argv[])
MPI initialization wrapper Process ID (myrank), Number of processes (nproc), Number of threads (nthreads), and pointer to the standard output (stdoutMPI) are specified here.
Author
Mitsuaki Kawamura (The University of Tokyo)
Definition at line 44 of file wrapperMPI.cpp.
References exitMPI(), myrank, nproc, nthreads, splash(), and stdoutMPI.
Referenced by main().
{
 #ifdef __MPI
   int ierr;
   ierr = MPI_Init(&argc, &argv);
   ierr = MPI_Comm_size(MPI_COMM_WORLD, &nproc);
   ierr = MPI_Comm_rank(MPI_COMM_WORLD, &myrank);
   if(ierr != 0) exitMPI(ierr);
 #else
   nproc = 1;
   myrank = 0;
 #endif
   if (myrank == 0) stdoutMPI = stdout;
   else stdoutMPI = fopen("/dev/null", "w");
   splash();
 #pragma omp parallel default(none) shared(nthreads)
 #pragma omp master
 #ifdef _OPENMP
   nthreads = omp_get_num_threads();
 #else
   nthreads=1;
 #endif
   fprintf(stdoutMPI, "\n\n#####  Parallelization Info.  #####\n\n");
   fprintf(stdoutMPI, "  OpenMP threads : %d\n", nthreads);
   fprintf(stdoutMPI, "  MPI PEs : %d \n\n", nproc);
 }/*void InitializeMPI(int argc, char *argv[])*/
MaxMPI_d()
double MaxMPI_d (double dvalue)
MPI wrapper function to obtain maximum Double across processes.
Returns
Maximum value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] dvalue Value to be maximized
Definition at line 188 of file wrapperMPI.cpp.
References exitMPI().
Referenced by check().
  {
 #ifdef __MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &dvalue, 1,
     MPI_DOUBLE, MPI_MAX, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(dvalue);
 }/*double MaxMPI_d*/
MaxMPI_li()
long int MaxMPI_li (long int idim)
MPI wrapper function to obtain maximum unsigned long integer across processes.
Returns
Maximum value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] idim Value to be maximized
Definition at line 171 of file wrapperMPI.cpp.
References exitMPI().
Referenced by check(), MakeExcitedList(), and setmem_large().
  {
 #ifdef __MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &idim, 1,
     MPI_LONG, MPI_MAX, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(idim);
 }/*long int MaxMPI_li*/
MultiVecProdMPI()
void MultiVecProdMPI (long int ndim, int nstate, std::complex< double > ** v1, std::complex< double > ** v2, std::complex< double > * prod)
Compute conjugate scaler product of process-distributed vector \({\bf v}_1^* \cdot {\bf v}_2\).
Parameters
[in] ndim Local dimension of vector
[in] v1 [ndim] vector to be producted
[in] v2 [ndim] vector to be producted
Definition at line 401 of file wrapperMPI.cpp.
References SumMPI_cv().
Referenced by expec_cisajs_Hubbard(), expec_cisajs_HubbardGC(), expec_cisajs_SpinGCGeneral(), expec_cisajs_SpinGCHalf(), expec_cisajs_SpinGeneral(), expec_cisajs_SpinHalf(), expec_cisajscktalt_Hubbard(), expec_cisajscktalt_HubbardGC(), expec_cisajscktalt_SpinGCGeneral(), expec_cisajscktalt_SpinGCHalf(), expec_cisajscktalt_SpinGeneral(), and expec_cisajscktalt_SpinHalf().
   {
   long int idim;
   int istate;
   for (istate = 0; istate < nstate; istate++) prod[istate] = 0.0;
   for (idim = 1; idim <= ndim; idim++) {
     for (istate = 0; istate < nstate; istate++) {
       prod[istate] += conj(v1[idim][istate])*v2[idim][istate];
     }
   }
   SumMPI_cv(nstate, prod);
 }/*void MultiVecProdMPI*/
NormMPI_dc()
double NormMPI_dc (long int idim, std::complex< double > * _v1)
Compute norm of process-distributed vector \(|{\bf v}_1|^2\).
Returns
Norm \(|{\bf v}_1|^2\)
Parameters
[in] idim Local dimension of vector
[in] _v1 [idim] vector to be producted
Definition at line 321 of file wrapperMPI.cpp.
References SumMPI_d().
Referenced by CalcSpectrumByBiCG().
  {
   double dnorm =0;
   long int i;
   dnorm = 0.0;
 #pragma omp parallel for default(none) private(i) \
 shared(_v1, idim) reduction(+:dnorm)
     for (i = 1; i <= idim; i++)
       dnorm += real(conj(_v1[i])*_v1[i]);
 #ifdef __MPI
   dnorm = SumMPI_d(dnorm);
 #endif
   return dnorm;
 }/*double NormMPI_dc*/
NormMPI_dv()
void NormMPI_dv (long int ndim, int nstate, std::complex< double > ** _v1, double * dnorm)
Compute norm of process-distributed vector \(|{\bf v}_1|^2\).
Returns
Norm \(|{\bf v}_1|^2\)
Parameters
[in] ndim Local dimension of vector
[in] _v1 [idim] vector to be producted
Definition at line 344 of file wrapperMPI.cpp.
References SumMPI_dv().
Referenced by Initialize_wave(), LOBPCG_Main(), and Multiply().
   {
   long int idim;
   int istate;
   for (istate = 0; istate < nstate; istate++) dnorm[istate] = 0.0;
   for (idim = 1; idim <= ndim; idim++) {
     for (istate = 0; istate < nstate; istate++) {
       dnorm[istate] += real(conj(_v1[idim][istate])*_v1[idim][istate]);
     }
   }
   SumMPI_dv(nstate, dnorm);
   for (istate = 0; istate < nstate; istate++) dnorm[istate] = sqrt(dnorm[istate]);
 }/*double NormMPI_cv*/
SendRecv_cv()
void SendRecv_cv (int origin, long int nMsgS, long int nMsgR, std::complex< double > * vecs, std::complex< double > * vecr)
Wrapper of MPI_Sendrecv for std::complex<double> number. When we pass a message longer than 2^31-1 (max of int: 2147483647), we need to divide it.
Definition at line 424 of file wrapperMPI.cpp.
References exitMPI().
Referenced by X_Ajt_MPI(), X_child_CisAit_GeneralSpin_MPIdouble(), X_child_CisAit_spin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIsingle(), X_child_CisAjt_MPIdouble(), X_child_CisAjt_MPIsingle(), X_child_CisAjtCkuAku_Hubbard_MPI(), X_child_CisAjtCkuAlv_Hubbard_MPI(), X_child_general_hopp_MPIdouble(), X_child_general_hopp_MPIsingle(), X_child_general_int_spin_MPIdouble(), X_child_general_int_spin_MPIsingle(), X_child_general_int_spin_TotalS_MPIdouble(), X_Cis_MPI(), X_GC_Ajt_MPI(), X_GC_child_CisAisCjuAjv_GeneralSpin_MPIdouble(), X_GC_child_CisAisCjuAjv_GeneralSpin_MPIsingle(), X_GC_child_CisAisCjuAjv_spin_MPIdouble(), X_GC_child_CisAisCjuAjv_spin_MPIsingle(), X_GC_child_CisAit_GeneralSpin_MPIdouble(), X_GC_child_CisAit_spin_MPIdouble(), X_GC_child_CisAitCiuAiv_spin_MPIdouble(), X_GC_child_CisAitCiuAiv_spin_MPIsingle(), X_GC_child_CisAitCjuAju_GeneralSpin_MPIdouble(), X_GC_child_CisAitCjuAju_spin_MPIdouble(), X_GC_child_CisAitCjuAjv_GeneralSpin_MPIdouble(), X_GC_child_CisAitCjuAjv_GeneralSpin_MPIsingle(), X_GC_child_CisAjtCkuAku_Hubbard_MPI(), X_GC_child_CisAjtCkuAlv_Hubbard_MPI(), X_GC_child_general_hopp_MPIdouble(), X_GC_child_general_hopp_MPIsingle(), and X_GC_Cis_MPI().
   {
 #ifdef __MPI
   int ierr, two31m1 = 2147483647, modMsg, nMsgS2, nMsgR2;
   long int nMsg, nnMsg, iMsg, sMsgR, sMsgS;
   MPI_Status statusMPI;
   if (nMsgS > nMsgR) nMsg = nMsgS;
   else nMsg = nMsgR;
   nnMsg = nMsg / two31m1;
   modMsg = nMsg % two31m1;
   if (modMsg != 0) nnMsg += 1;
   sMsgS = 0;
   sMsgR = 0;
   for (iMsg = 0; iMsg < nnMsg; iMsg++) {
     nMsgS2 = nMsgS / nnMsg;
     nMsgR2 = nMsgR / nnMsg;
     if (iMsg < nMsgS % nnMsg) nMsgS2 += 1;
     if (iMsg < nMsgR % nnMsg) nMsgR2 += 1;
     ierr = MPI_Sendrecv(&vecs[sMsgS], nMsgS2, MPI_DOUBLE_COMPLEX, origin, 0,
                         &vecr[sMsgR], nMsgR2, MPI_DOUBLE_COMPLEX, origin, 0,
                         MPI_COMM_WORLD, &statusMPI);
     if (ierr != 0) exitMPI(-1);
     sMsgS += nMsgS2;
     sMsgR += nMsgR2;
   }
 #endif
 }/*void SendRecv_cv*/
SendRecv_i()
long int SendRecv_i (int origin, long int isend)
Wrapper of MPI_Sendrecv for long integer number.
Definition at line 504 of file wrapperMPI.cpp.
References exitMPI().
Referenced by X_Ajt_MPI(), X_child_CisAit_GeneralSpin_MPIdouble(), X_child_CisAit_spin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIsingle(), X_child_CisAjt_MPIdouble(), X_child_CisAjt_MPIsingle(), X_child_CisAjtCkuAku_Hubbard_MPI(), X_child_CisAjtCkuAlv_Hubbard_MPI(), X_child_general_hopp_MPIdouble(), X_child_general_hopp_MPIsingle(), X_child_general_int_spin_MPIdouble(), X_child_general_int_spin_MPIsingle(), X_child_general_int_spin_TotalS_MPIdouble(), X_Cis_MPI(), X_GC_Ajt_MPI(), X_GC_child_CisAisCjuAjv_spin_MPIdouble(), X_GC_child_CisAisCjuAjv_spin_MPIsingle(), X_GC_child_CisAit_spin_MPIdouble(), X_GC_child_CisAitCiuAiv_spin_MPIdouble(), X_GC_child_CisAitCiuAiv_spin_MPIsingle(), X_GC_child_CisAitCjuAju_spin_MPIdouble(), X_GC_child_CisAjtCkuAku_Hubbard_MPI(), X_GC_child_CisAjtCkuAlv_Hubbard_MPI(), X_GC_child_general_hopp_MPIdouble(), X_GC_child_general_hopp_MPIsingle(), and X_GC_Cis_MPI().
   {
 #ifdef __MPI
   int ierr;
   MPI_Status statusMPI;
   long int ircv;
   ierr = MPI_Sendrecv(&isend, 1, MPI_LONG, origin, 0,
                       &ircv,  1, MPI_LONG, origin, 0,
                       MPI_COMM_WORLD, &statusMPI);
   if (ierr != 0) exitMPI(ierr);
   return ircv;
 #else
   return isend;
 #endif
 }/*void SendRecv_i*/
SendRecv_iv()
void SendRecv_iv (int origin, long int nMsgS, long int nMsgR, long int * vecs, long int * vecr)
Wrapper of MPI_Sendrecv for long integer number. When we pass a message longer than 2^31-1 (max of int: 2147483647), we need to divide it.
Definition at line 465 of file wrapperMPI.cpp.
References exitMPI().
Referenced by X_Ajt_MPI(), X_child_CisAit_GeneralSpin_MPIdouble(), X_child_CisAit_spin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIdouble(), X_child_CisAitCjuAjv_GeneralSpin_MPIsingle(), X_child_CisAjt_MPIdouble(), X_child_CisAjt_MPIsingle(), X_child_CisAjtCkuAku_Hubbard_MPI(), X_child_CisAjtCkuAlv_Hubbard_MPI(), X_child_general_hopp_MPIdouble(), X_child_general_hopp_MPIsingle(), X_child_general_int_spin_MPIdouble(), X_child_general_int_spin_MPIsingle(), X_child_general_int_spin_TotalS_MPIdouble(), and X_Cis_MPI().
   {
 #ifdef __MPI
   int ierr, two31m1 = 2147483647, modMsg, nMsgS2, nMsgR2;
   long int nMsg, nnMsg, iMsg, sMsgR, sMsgS;
   MPI_Status statusMPI;
   if (nMsgS > nMsgR) nMsg = nMsgS;
   else nMsg = nMsgR;
   nnMsg = nMsg / two31m1;
   modMsg = nMsg % two31m1;
   if (modMsg != 0) nnMsg += 1;
   sMsgS = 0;
   sMsgR = 0;
   for (iMsg = 0; iMsg < nnMsg; iMsg++) {
     nMsgS2 = nMsgS / nnMsg;
     nMsgR2 = nMsgR / nnMsg;
     if (iMsg < nMsgS % nnMsg) nMsgS2 += 1;
     if (iMsg < nMsgR % nnMsg) nMsgR2 += 1;
     ierr = MPI_Sendrecv(&vecs[sMsgS], nMsgS2, MPI_LONG, origin, 0,
                         &vecr[sMsgR], nMsgR2, MPI_LONG, origin, 0,
                         MPI_COMM_WORLD, &statusMPI);
     if (ierr != 0) exitMPI(-1);
     sMsgS += nMsgS2;
     sMsgR += nMsgR2;
   }
 #endif
 }/*void SendRecv_iv*/
SumMPI_cv()
void SumMPI_cv (int nnorm, std::complex< double > * norm)
MPI wrapper function to obtain sum of Double array across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] norm Value to be summed
Definition at line 254 of file wrapperMPI.cpp.
References exitMPI().
Referenced by LOBPCG_Main(), and MultiVecProdMPI().
   {
 #ifdef __MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, norm, nnorm,
     MPI_DOUBLE_COMPLEX, MPI_SUM, MPI_COMM_WORLD);
   if (ierr != 0) exitMPI(-1);
 #endif
 }/*void SumMPI_cv*/
SumMPI_d()
double SumMPI_d (double norm)
MPI wrapper function to obtain sum of Double across processes.
Returns
Sumed value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] norm Value to be summed
Definition at line 222 of file wrapperMPI.cpp.
References exitMPI().
Referenced by MultiplyForTEM(), and NormMPI_dc().
  {
 #ifdef __MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &norm, 1,
     MPI_DOUBLE_PRECISION, MPI_SUM, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(norm);
 }/*double SumMPI_d*/
SumMPI_dc()
std::complex<double> SumMPI_dc (std::complex< double > norm)
MPI wrapper function to obtain sum of Double complex across processes.
Returns
Sumed value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] norm Value to be summed
Definition at line 205 of file wrapperMPI.cpp.
References exitMPI().
Referenced by VecProdMPI().
  {
 #ifdef __MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &norm, 1,
     MPI_DOUBLE_COMPLEX, MPI_SUM, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(norm);
 }/*std::complex<double> SumMPI_dc*/
SumMPI_dv()
void SumMPI_dv (int nnorm, double * norm)
MPI wrapper function to obtain sum of Double array across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] norm Value to be summed
Definition at line 238 of file wrapperMPI.cpp.
References exitMPI().
Referenced by expec_energy_flct(), expec_energy_flct_GeneralSpin(), expec_energy_flct_GeneralSpinGC(), expec_energy_flct_HalfSpin(), expec_energy_flct_HalfSpinGC(), expec_energy_flct_Hubbard(), expec_energy_flct_HubbardGC(), LOBPCG_Main(), NormMPI_dv(), totalspin_Hubbard(), totalspin_HubbardGC(), totalspin_Spin(), and totalspin_SpinGC().
   {
 #ifdef __MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, norm, nnorm,
     MPI_DOUBLE_PRECISION, MPI_SUM, MPI_COMM_WORLD);
   if (ierr != 0) exitMPI(-1);
 #endif
 }/*void SumMPI_dv*/
SumMPI_i()
int SumMPI_i (int idim)
MPI wrapper function to obtain sum of integer across processes.
Returns
Sumed value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] idim Value to be summed
Definition at line 288 of file wrapperMPI.cpp.
References exitMPI().
Referenced by CheckMPI_Summary().
   {
 #ifdef __MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &idim, 1,
                        MPI_INT, MPI_SUM, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(idim);
 }/*int SumMPI_i*/
SumMPI_li()
long int SumMPI_li (long int idim)
MPI wrapper function to obtain sum of unsigned long integer across processes.
Returns
Sumed value across processes.
Author
Mitsuaki Kawamura (The University of Tokyo)
Parameters
[in] idim Value to be summed
Definition at line 271 of file wrapperMPI.cpp.
References exitMPI().
Referenced by CheckMPI_Summary(), and Initialize_wave().
  {
 #ifdef __MPI
   int ierr;
   ierr = MPI_Allreduce(MPI_IN_PLACE, &idim, 1,
     MPI_LONG, MPI_SUM, MPI_COMM_WORLD);
   if(ierr != 0) exitMPI(-1);
 #endif
   return(idim);
 }/*long int SumMPI_li*/
VecProdMPI()
std::complex<double> VecProdMPI (long int ndim, std::complex< double > * v1, std::complex< double > * v2)
Compute conjugate scaler product of process-distributed vector \({\bf v}_1^* \cdot {\bf v}_2\).
Returns
Conjugate scaler product \({\bf v}_1^* \cdot {\bf v}_2\)
Parameters
[in] ndim Local dimension of vector
[in] v1 [ndim] vector to be producted
[in] v2 [ndim] vector to be producted
Definition at line 367 of file wrapperMPI.cpp.
References nthreads, and SumMPI_dc().
Referenced by CalcSpectrumByBiCG().
  {
   long int idim;
   std::complex<double> prod, *prod_thr;
   int mythread;
   prod_thr = cd_1d_allocate(nthreads);
 #pragma omp parallel default(none) shared(v1,v2,ndim,prod,prod_thr) private(idim,mythread)
   {
 #ifdef _OPENMP
     mythread = omp_get_thread_num();
 #else
     mythread = 0;
 #endif
 #pragma omp for
     for (idim = 1; idim <= ndim; idim++)
       prod_thr[mythread] += conj(v1[idim]) * v2[idim];
   }
   prod = 0.0;
   for (mythread = 0; mythread < nthreads; mythread++)
     prod += prod_thr[mythread];
   free_cd_1d_allocate(prod_thr);
   prod = SumMPI_dc(prod);
   return(prod);
 }/*std::complex<double> VecProdMPI*/