/* HPhi  -  Quantum Lattice Model Simulator */
/* Copyright (C) 2015 The University of Tokyo */

/* This program is free software: you can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation, either version 3 of the License, or */
/* (at your option) any later version. */

/* This program is distributed in the hope that it will be useful, */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the */
/* GNU General Public License for more details. */

/* You should have received a copy of the GNU General Public License */
/* along with this program.  If not, see <http://www.gnu.org/licenses/>. */
/*-------------------------------------------------------------*/
#include "bitcalc.hpp"
#include "mltplyCommon.hpp"
#include "PairEx.hpp"
#include "PairExHubbard.hpp"
#include "PairExSpin.hpp"
#include "global.hpp"
#include "DefCommon.hpp"
#include <complex>

/**
 * @file
 *
 * @brief  Calculating the pair excited state generated by the pair operator\n
 * @f[ \sum_{i,j, \sigma_1, \sigma_2} h_{i,\sigma_1, j, \sigma_2} c_{i\sigma_1} c_{j\sigma_2} (a_{i\sigma_1} a_{j\sigma_2})@f]
 * , where @f$ c_{i\sigma_1} (a_{i\sigma_1})@f$ indicates a creation (anti-creation) operator at @f$i@f$-th site with @f$ \sigma_1 @f$ spin.
 *
 * @version 1.2
 * @author Kazuyoshi Yoshimi (The University of Tokyo)
 */

///
/// \brief Calculating the pair excited state by the pair operator; \n
/// @f[ \sum_{i,j, \sigma_1, \sigma_2} h_{i,\sigma_1, j, \sigma_2} c_{i\sigma_1} c_{j\sigma_2} (a_{i\sigma_1} a_{j\sigma_2})@f]
/// , where @f$ c_{i\sigma_1} (a_{i\sigma_1})@f$ indicates a creation (anti-creation) operator at @f$i@f$-th site with @f$ \sigma_1 @f$ spin.
/// Target System: Hubbard, Kondo, Spin.
/// \param X [in] define list to get and put information of calculation
/// \param tmp_v0 [in, out] Result @f$ v_0 += H v_1 @f$.
/// \param tmp_v1 [in] The wave vector @f$ v_1 @f$ to be mltiplied by the Hamiltonian @f$ H v_1 @f$.
/// \returns TRUE: Normally finished
/// \returns FALSE: Unnormally finished
/// \author Kazuyoshi Yoshimi (The University of Tokyo)
/// \version 1.2
int GetPairExcitedState
(
  int nstate,
  std::complex<double> **tmp_v0,
  std::complex<double> **tmp_v1,
  int iEx
)
{
  int iret;
  long int irght, ilft, ihfbit;

  //  i_max = Check::idim_max;
  if (Def::iFlgGeneralSpin == FALSE) {
    if (GetSplitBitByModel(Def::Nsite, Def::iCalcModel, &irght, &ilft, &ihfbit) != 0) {
      return -1;
    }
  }
  else {
    if (GetSplitBitForGeneralSpin(Def::Nsite, &ihfbit, Def::SiteToBit) != 0) {
      return -1;
    }
  }

  Large::i_max = Check::idim_maxOrg;
  Large::irght = irght;
  Large::ilft = ilft;
  Large::ihfbit = ihfbit;
  Large::mode = M_CALCSPEC;

  switch (Def::iCalcModel) {
  case DC::HubbardGC:
    iret = GetExcitedState::Pair::HubbardGC(nstate, tmp_v0, tmp_v1, iEx);
    break;

  case DC::KondoGC:
  case DC::Hubbard:
  case DC::Kondo:
    iret = GetExcitedState::Pair::Hubbard(nstate, tmp_v0, tmp_v1, iEx);
    break;

  case DC::Spin: // for the Sz-conserved spin system
    iret = GetExcitedState::Pair::Spin::main(nstate, tmp_v0, tmp_v1, iEx);
    break;

  case DC::SpinGC:
    iret = GetExcitedState::Pair::SpinGC::main(nstate, tmp_v0, tmp_v1, iEx);
    break;

  default:
    iret = FALSE;
    break;
  }

  return iret;
}
